// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: svc/environment/v1/service.proto

package environmentv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/minitape/api/go/svc/environment/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EnvironmentServiceName is the fully-qualified name of the EnvironmentService service.
	EnvironmentServiceName = "svc.environment.v1.EnvironmentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EnvironmentServiceListResourceProcedure is the fully-qualified name of the EnvironmentService's
	// ListResource RPC.
	EnvironmentServiceListResourceProcedure = "/svc.environment.v1.EnvironmentService/ListResource"
	// EnvironmentServiceTrimProcedure is the fully-qualified name of the EnvironmentService's Trim RPC.
	EnvironmentServiceTrimProcedure = "/svc.environment.v1.EnvironmentService/Trim"
)

// EnvironmentServiceClient is a client for the svc.environment.v1.EnvironmentService service.
type EnvironmentServiceClient interface {
	ListResource(context.Context, *connect.Request[v1.ListResourceRequest]) (*connect.Response[v1.ListResourceResponse], error)
	Trim(context.Context, *connect.Request[v1.TrimRequest]) (*connect.Response[v1.TrimResponse], error)
}

// NewEnvironmentServiceClient constructs a client for the svc.environment.v1.EnvironmentService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEnvironmentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EnvironmentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	environmentServiceMethods := v1.File_svc_environment_v1_service_proto.Services().ByName("EnvironmentService").Methods()
	return &environmentServiceClient{
		listResource: connect.NewClient[v1.ListResourceRequest, v1.ListResourceResponse](
			httpClient,
			baseURL+EnvironmentServiceListResourceProcedure,
			connect.WithSchema(environmentServiceMethods.ByName("ListResource")),
			connect.WithClientOptions(opts...),
		),
		trim: connect.NewClient[v1.TrimRequest, v1.TrimResponse](
			httpClient,
			baseURL+EnvironmentServiceTrimProcedure,
			connect.WithSchema(environmentServiceMethods.ByName("Trim")),
			connect.WithClientOptions(opts...),
		),
	}
}

// environmentServiceClient implements EnvironmentServiceClient.
type environmentServiceClient struct {
	listResource *connect.Client[v1.ListResourceRequest, v1.ListResourceResponse]
	trim         *connect.Client[v1.TrimRequest, v1.TrimResponse]
}

// ListResource calls svc.environment.v1.EnvironmentService.ListResource.
func (c *environmentServiceClient) ListResource(ctx context.Context, req *connect.Request[v1.ListResourceRequest]) (*connect.Response[v1.ListResourceResponse], error) {
	return c.listResource.CallUnary(ctx, req)
}

// Trim calls svc.environment.v1.EnvironmentService.Trim.
func (c *environmentServiceClient) Trim(ctx context.Context, req *connect.Request[v1.TrimRequest]) (*connect.Response[v1.TrimResponse], error) {
	return c.trim.CallUnary(ctx, req)
}

// EnvironmentServiceHandler is an implementation of the svc.environment.v1.EnvironmentService
// service.
type EnvironmentServiceHandler interface {
	ListResource(context.Context, *connect.Request[v1.ListResourceRequest]) (*connect.Response[v1.ListResourceResponse], error)
	Trim(context.Context, *connect.Request[v1.TrimRequest]) (*connect.Response[v1.TrimResponse], error)
}

// NewEnvironmentServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEnvironmentServiceHandler(svc EnvironmentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	environmentServiceMethods := v1.File_svc_environment_v1_service_proto.Services().ByName("EnvironmentService").Methods()
	environmentServiceListResourceHandler := connect.NewUnaryHandler(
		EnvironmentServiceListResourceProcedure,
		svc.ListResource,
		connect.WithSchema(environmentServiceMethods.ByName("ListResource")),
		connect.WithHandlerOptions(opts...),
	)
	environmentServiceTrimHandler := connect.NewUnaryHandler(
		EnvironmentServiceTrimProcedure,
		svc.Trim,
		connect.WithSchema(environmentServiceMethods.ByName("Trim")),
		connect.WithHandlerOptions(opts...),
	)
	return "/svc.environment.v1.EnvironmentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EnvironmentServiceListResourceProcedure:
			environmentServiceListResourceHandler.ServeHTTP(w, r)
		case EnvironmentServiceTrimProcedure:
			environmentServiceTrimHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEnvironmentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEnvironmentServiceHandler struct{}

func (UnimplementedEnvironmentServiceHandler) ListResource(context.Context, *connect.Request[v1.ListResourceRequest]) (*connect.Response[v1.ListResourceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("svc.environment.v1.EnvironmentService.ListResource is not implemented"))
}

func (UnimplementedEnvironmentServiceHandler) Trim(context.Context, *connect.Request[v1.TrimRequest]) (*connect.Response[v1.TrimResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("svc.environment.v1.EnvironmentService.Trim is not implemented"))
}
