// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file svc/query/v1/trace_service.proto (package svc.query.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Span, Trace } from "../../../types/v1/otel_tracing_pb";
import { file_types_v1_otel_tracing } from "../../../types/v1/otel_tracing_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file svc/query/v1/trace_service.proto.
 */
export const file_svc_query_v1_trace_service: GenFile = /*@__PURE__*/
  fileDesc("CiBzdmMvcXVlcnkvdjEvdHJhY2Vfc2VydmljZS5wcm90bxIMc3ZjLnF1ZXJ5LnYxIlgKD0dldFRyYWNlUmVxdWVzdBIWCg5lbnZpcm9ubWVudF9pZBgBIAEoAxITCgh0cmFjZV9pZBjJASABKAlIABISCgdzcGFuX2lkGMoBIAEoCUgAQgQKAmJ5IjIKEEdldFRyYWNlUmVzcG9uc2USHgoFdHJhY2UYASABKAsyDy50eXBlcy52MS5UcmFjZSI5Cg5HZXRTcGFuUmVxdWVzdBIWCg5lbnZpcm9ubWVudF9pZBgBIAEoAxIPCgdzcGFuX2lkGAIgASgJIi8KD0dldFNwYW5SZXNwb25zZRIcCgRzcGFuGAEgASgLMg4udHlwZXMudjEuU3BhbjKhAQoMVHJhY2VTZXJ2aWNlEkkKCEdldFRyYWNlEh0uc3ZjLnF1ZXJ5LnYxLkdldFRyYWNlUmVxdWVzdBoeLnN2Yy5xdWVyeS52MS5HZXRUcmFjZVJlc3BvbnNlEkYKB0dldFNwYW4SHC5zdmMucXVlcnkudjEuR2V0U3BhblJlcXVlc3QaHS5zdmMucXVlcnkudjEuR2V0U3BhblJlc3BvbnNlQqgBChBjb20uc3ZjLnF1ZXJ5LnYxQhFUcmFjZVNlcnZpY2VQcm90b1ABWi9naXRodWIuY29tL21pbml0YXBlL2FwaS9nby9zdmMvcXVlcnkvdjE7cXVlcnl2MaICA1NRWKoCDFN2Yy5RdWVyeS5WMcoCDFN2Y1xRdWVyeVxWMeICGFN2Y1xRdWVyeVxWMVxHUEJNZXRhZGF0YeoCDlN2Yzo6UXVlcnk6OlYxYgZwcm90bzM", [file_types_v1_otel_tracing]);

/**
 * @generated from message svc.query.v1.GetTraceRequest
 */
export type GetTraceRequest = Message<"svc.query.v1.GetTraceRequest"> & {
  /**
   * @generated from field: int64 environment_id = 1;
   */
  environmentId: bigint;

  /**
   * @generated from oneof svc.query.v1.GetTraceRequest.by
   */
  by: {
    /**
     * @generated from field: string trace_id = 201;
     */
    value: string;
    case: "traceId";
  } | {
    /**
     * @generated from field: string span_id = 202;
     */
    value: string;
    case: "spanId";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message svc.query.v1.GetTraceRequest.
 * Use `create(GetTraceRequestSchema)` to create a new message.
 */
export const GetTraceRequestSchema: GenMessage<GetTraceRequest> = /*@__PURE__*/
  messageDesc(file_svc_query_v1_trace_service, 0);

/**
 * @generated from message svc.query.v1.GetTraceResponse
 */
export type GetTraceResponse = Message<"svc.query.v1.GetTraceResponse"> & {
  /**
   * @generated from field: types.v1.Trace trace = 1;
   */
  trace?: Trace;
};

/**
 * Describes the message svc.query.v1.GetTraceResponse.
 * Use `create(GetTraceResponseSchema)` to create a new message.
 */
export const GetTraceResponseSchema: GenMessage<GetTraceResponse> = /*@__PURE__*/
  messageDesc(file_svc_query_v1_trace_service, 1);

/**
 * @generated from message svc.query.v1.GetSpanRequest
 */
export type GetSpanRequest = Message<"svc.query.v1.GetSpanRequest"> & {
  /**
   * @generated from field: int64 environment_id = 1;
   */
  environmentId: bigint;

  /**
   * @generated from field: string span_id = 2;
   */
  spanId: string;
};

/**
 * Describes the message svc.query.v1.GetSpanRequest.
 * Use `create(GetSpanRequestSchema)` to create a new message.
 */
export const GetSpanRequestSchema: GenMessage<GetSpanRequest> = /*@__PURE__*/
  messageDesc(file_svc_query_v1_trace_service, 2);

/**
 * @generated from message svc.query.v1.GetSpanResponse
 */
export type GetSpanResponse = Message<"svc.query.v1.GetSpanResponse"> & {
  /**
   * @generated from field: types.v1.Span span = 1;
   */
  span?: Span;
};

/**
 * Describes the message svc.query.v1.GetSpanResponse.
 * Use `create(GetSpanResponseSchema)` to create a new message.
 */
export const GetSpanResponseSchema: GenMessage<GetSpanResponse> = /*@__PURE__*/
  messageDesc(file_svc_query_v1_trace_service, 3);

/**
 * @generated from service svc.query.v1.TraceService
 */
export const TraceService: GenService<{
  /**
   * @generated from rpc svc.query.v1.TraceService.GetTrace
   */
  getTrace: {
    methodKind: "unary";
    input: typeof GetTraceRequestSchema;
    output: typeof GetTraceResponseSchema;
  },
  /**
   * @generated from rpc svc.query.v1.TraceService.GetSpan
   */
  getSpan: {
    methodKind: "unary";
    input: typeof GetSpanRequestSchema;
    output: typeof GetSpanResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_svc_query_v1_trace_service, 0);

