// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file svc/cliupdate/v1/service.proto (package svc.cliupdate.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { ReqMeta, ResMeta } from "../../../types/v1/meta_pb";
import { file_types_v1_meta } from "../../../types/v1/meta_pb";
import type { Version } from "../../../types/v1/version_pb";
import { file_types_v1_version } from "../../../types/v1/version_pb";
import type { VersionArtifact } from "../../../types/v1/version_artifact_pb";
import { file_types_v1_version_artifact } from "../../../types/v1/version_artifact_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file svc/cliupdate/v1/service.proto.
 */
export const file_svc_cliupdate_v1_service: GenFile = /*@__PURE__*/
  fileDesc("Ch5zdmMvY2xpdXBkYXRlL3YxL3NlcnZpY2UucHJvdG8SEHN2Yy5jbGl1cGRhdGUudjEi9gEKFEdldE5leHRVcGRhdGVSZXF1ZXN0EhQKDHByb2plY3RfbmFtZRgBIAEoCRIqCg9jdXJyZW50X3ZlcnNpb24YAiABKAsyES50eXBlcy52MS5WZXJzaW9uEhwKFG1hY2hpbmVfYXJjaGl0ZWN0dXJlGAMgASgJEiAKGG1hY2hpbmVfb3BlcmF0aW5nX3N5c3RlbRgEIAEoCRIhChRyZWxlYXNlX2NoYW5uZWxfbmFtZRgFIAEoCUgAiAEBEiAKBG1ldGEY6AcgASgLMhEudHlwZXMudjEuUmVxTWV0YUIXChVfcmVsZWFzZV9jaGFubmVsX25hbWUilAEKFUdldE5leHRVcGRhdGVSZXNwb25zZRInCgxuZXh0X3ZlcnNpb24YASABKAsyES50eXBlcy52MS5WZXJzaW9uEjAKDW5leHRfYXJ0aWZhY3QYAiABKAsyGS50eXBlcy52MS5WZXJzaW9uQXJ0aWZhY3QSIAoEbWV0YRjoByABKAsyES50eXBlcy52MS5SZXNNZXRhMnMKDVVwZGF0ZVNlcnZpY2USYgoNR2V0TmV4dFVwZGF0ZRImLnN2Yy5jbGl1cGRhdGUudjEuR2V0TmV4dFVwZGF0ZVJlcXVlc3QaJy5zdmMuY2xpdXBkYXRlLnYxLkdldE5leHRVcGRhdGVSZXNwb25zZSIAQr8BChRjb20uc3ZjLmNsaXVwZGF0ZS52MUIMU2VydmljZVByb3RvUAFaN2dpdGh1Yi5jb20vbWluaXRhcGUvYXBpL2dvL3N2Yy9jbGl1cGRhdGUvdjE7Y2xpdXBkYXRldjGiAgNTQ1iqAhBTdmMuQ2xpdXBkYXRlLlYxygIQU3ZjXENsaXVwZGF0ZVxWMeICHFN2Y1xDbGl1cGRhdGVcVjFcR1BCTWV0YWRhdGHqAhJTdmM6OkNsaXVwZGF0ZTo6VjFiBnByb3RvMw", [file_types_v1_meta, file_types_v1_version, file_types_v1_version_artifact]);

/**
 * @generated from message svc.cliupdate.v1.GetNextUpdateRequest
 */
export type GetNextUpdateRequest = Message<"svc.cliupdate.v1.GetNextUpdateRequest"> & {
  /**
   * @generated from field: string project_name = 1;
   */
  projectName: string;

  /**
   * @generated from field: types.v1.Version current_version = 2;
   */
  currentVersion?: Version;

  /**
   * @generated from field: string machine_architecture = 3;
   */
  machineArchitecture: string;

  /**
   * @generated from field: string machine_operating_system = 4;
   */
  machineOperatingSystem: string;

  /**
   * @generated from field: optional string release_channel_name = 5;
   */
  releaseChannelName?: string;

  /**
   * @generated from field: types.v1.ReqMeta meta = 1000;
   */
  meta?: ReqMeta;
};

/**
 * Describes the message svc.cliupdate.v1.GetNextUpdateRequest.
 * Use `create(GetNextUpdateRequestSchema)` to create a new message.
 */
export const GetNextUpdateRequestSchema: GenMessage<GetNextUpdateRequest> = /*@__PURE__*/
  messageDesc(file_svc_cliupdate_v1_service, 0);

/**
 * @generated from message svc.cliupdate.v1.GetNextUpdateResponse
 */
export type GetNextUpdateResponse = Message<"svc.cliupdate.v1.GetNextUpdateResponse"> & {
  /**
   * @generated from field: types.v1.Version next_version = 1;
   */
  nextVersion?: Version;

  /**
   * @generated from field: types.v1.VersionArtifact next_artifact = 2;
   */
  nextArtifact?: VersionArtifact;

  /**
   * @generated from field: types.v1.ResMeta meta = 1000;
   */
  meta?: ResMeta;
};

/**
 * Describes the message svc.cliupdate.v1.GetNextUpdateResponse.
 * Use `create(GetNextUpdateResponseSchema)` to create a new message.
 */
export const GetNextUpdateResponseSchema: GenMessage<GetNextUpdateResponse> = /*@__PURE__*/
  messageDesc(file_svc_cliupdate_v1_service, 1);

/**
 * @generated from service svc.cliupdate.v1.UpdateService
 */
export const UpdateService: GenService<{
  /**
   * @generated from rpc svc.cliupdate.v1.UpdateService.GetNextUpdate
   */
  getNextUpdate: {
    methodKind: "unary";
    input: typeof GetNextUpdateRequestSchema;
    output: typeof GetNextUpdateResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_svc_cliupdate_v1_service, 0);

