// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/cursor.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/cursor.proto.
 */
export const file_types_v1_cursor: GenFile = /*@__PURE__*/
  fileDesc("ChV0eXBlcy92MS9jdXJzb3IucHJvdG8SCHR5cGVzLnYxIhgKBkN1cnNvchIOCgZvcGFxdWUYASABKAxCiQEKDGNvbS50eXBlcy52MUILQ3Vyc29yUHJvdG9QAVorZ2l0aHViLmNvbS9taW5pdGFwZS9hcGkvZ28vdHlwZXMvdjE7dHlwZXN2MaICA1RYWKoCCFR5cGVzLlYxygIIVHlwZXNcVjHiAhRUeXBlc1xWMVxHUEJNZXRhZGF0YeoCCVR5cGVzOjpWMWIGcHJvdG8z");

/**
 * @generated from message types.v1.Cursor
 */
export type Cursor = Message<"types.v1.Cursor"> & {
  /**
   * @generated from field: bytes opaque = 1;
   */
  opaque: Uint8Array;
};

/**
 * Describes the message types.v1.Cursor.
 * Use `create(CursorSchema)` to create a new message.
 */
export const CursorSchema: GenMessage<Cursor> = /*@__PURE__*/
  messageDesc(file_types_v1_cursor, 0);

