// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/dashboard.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/dashboard.proto.
 */
export const file_types_v1_dashboard: GenFile = /*@__PURE__*/
  fileDesc("Chh0eXBlcy92MS9kYXNoYm9hcmQucHJvdG8SCHR5cGVzLnYxIoQBCglEYXNoYm9hcmQSJQoEbWV0YRgBIAEoCzIXLnR5cGVzLnYxLkRhc2hib2FyZE1ldGESJQoEc3BlYxgCIAEoCzIXLnR5cGVzLnYxLkRhc2hib2FyZFNwZWMSKQoGc3RhdHVzGAMgASgLMhkudHlwZXMudjEuRGFzaGJvYXJkU3RhdHVzIhsKDURhc2hib2FyZE1ldGESCgoCaWQYASABKAkiXAoNRGFzaGJvYXJkU3BlYxIMCgRuYW1lGAEgASgJEhMKC2Rlc2NyaXB0aW9uGAIgASgJEhMKC2lzX3JlYWRvbmx5GAMgASgIEhMKC3BlcnNlc19qc29uGAUgASgMIs8ECg9EYXNoYm9hcmRTdGF0dXMSLgoKY3JlYXRlZF9hdBgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASDgoGZXJyb3JzGAMgAygJEj0KB21hbmFnZWQYBCABKAsyKi50eXBlcy52MS5EYXNoYm9hcmRTdGF0dXMuTWFuYWdlZERhc2hib2FyZEgAEkEKCWdlbmVyYXRlZBgFIAEoCzIsLnR5cGVzLnYxLkRhc2hib2FyZFN0YXR1cy5HZW5lcmF0ZWREYXNoYm9hcmRIABI9CgdidWlsdGluGAYgASgLMioudHlwZXMudjEuRGFzaGJvYXJkU3RhdHVzLkJ1aWx0aW5EYXNoYm9hcmRIABI7CgZyZW1vdGUYByABKAsyKS50eXBlcy52MS5EYXNoYm9hcmRTdGF0dXMuUmVtb3RlRGFzaGJvYXJkSAAaIAoQTWFuYWdlZERhc2hib2FyZBIMCgRwYXRoGAEgASgJGjwKEkdlbmVyYXRlZERhc2hib2FyZBIMCgRwYXRoGAEgASgJEhgKEGRldGVjdGlvbl9yZWFzb24YAiABKAkaHgoQQnVpbHRpbkRhc2hib2FyZBIKCgJpZBgBIAEoCRpECg9SZW1vdGVEYXNoYm9hcmQSFgoOcmVwb3NpdG9yeV91cmwYASABKAkSDAoEcGF0aBgCIAEoCRILCgNyZWYYAyABKAlCCAoGb3JpZ2luQowBCgxjb20udHlwZXMudjFCDkRhc2hib2FyZFByb3RvUAFaK2dpdGh1Yi5jb20vbWluaXRhcGUvYXBpL2dvL3R5cGVzL3YxO3R5cGVzdjGiAgNUWFiqAghUeXBlcy5WMcoCCFR5cGVzXFYx4gIUVHlwZXNcVjFcR1BCTWV0YWRhdGHqAglUeXBlczo6VjFiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * @generated from message types.v1.Dashboard
 */
export type Dashboard = Message<"types.v1.Dashboard"> & {
  /**
   * @generated from field: types.v1.DashboardMeta meta = 1;
   */
  meta?: DashboardMeta;

  /**
   * @generated from field: types.v1.DashboardSpec spec = 2;
   */
  spec?: DashboardSpec;

  /**
   * @generated from field: types.v1.DashboardStatus status = 3;
   */
  status?: DashboardStatus;
};

/**
 * Describes the message types.v1.Dashboard.
 * Use `create(DashboardSchema)` to create a new message.
 */
export const DashboardSchema: GenMessage<Dashboard> = /*@__PURE__*/
  messageDesc(file_types_v1_dashboard, 0);

/**
 * @generated from message types.v1.DashboardMeta
 */
export type DashboardMeta = Message<"types.v1.DashboardMeta"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message types.v1.DashboardMeta.
 * Use `create(DashboardMetaSchema)` to create a new message.
 */
export const DashboardMetaSchema: GenMessage<DashboardMeta> = /*@__PURE__*/
  messageDesc(file_types_v1_dashboard, 1);

/**
 * @generated from message types.v1.DashboardSpec
 */
export type DashboardSpec = Message<"types.v1.DashboardSpec"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * @generated from field: bool is_readonly = 3;
   */
  isReadonly: boolean;

  /**
   * @generated from field: bytes perses_json = 5;
   */
  persesJson: Uint8Array;
};

/**
 * Describes the message types.v1.DashboardSpec.
 * Use `create(DashboardSpecSchema)` to create a new message.
 */
export const DashboardSpecSchema: GenMessage<DashboardSpec> = /*@__PURE__*/
  messageDesc(file_types_v1_dashboard, 2);

/**
 * @generated from message types.v1.DashboardStatus
 */
export type DashboardStatus = Message<"types.v1.DashboardStatus"> & {
  /**
   * @generated from field: google.protobuf.Timestamp created_at = 1;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 2;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: repeated string errors = 3;
   */
  errors: string[];

  /**
   * @generated from oneof types.v1.DashboardStatus.origin
   */
  origin: {
    /**
     * @generated from field: types.v1.DashboardStatus.ManagedDashboard managed = 4;
     */
    value: DashboardStatus_ManagedDashboard;
    case: "managed";
  } | {
    /**
     * @generated from field: types.v1.DashboardStatus.GeneratedDashboard generated = 5;
     */
    value: DashboardStatus_GeneratedDashboard;
    case: "generated";
  } | {
    /**
     * @generated from field: types.v1.DashboardStatus.BuiltinDashboard builtin = 6;
     */
    value: DashboardStatus_BuiltinDashboard;
    case: "builtin";
  } | {
    /**
     * @generated from field: types.v1.DashboardStatus.RemoteDashboard remote = 7;
     */
    value: DashboardStatus_RemoteDashboard;
    case: "remote";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message types.v1.DashboardStatus.
 * Use `create(DashboardStatusSchema)` to create a new message.
 */
export const DashboardStatusSchema: GenMessage<DashboardStatus> = /*@__PURE__*/
  messageDesc(file_types_v1_dashboard, 3);

/**
 * @generated from message types.v1.DashboardStatus.ManagedDashboard
 */
export type DashboardStatus_ManagedDashboard = Message<"types.v1.DashboardStatus.ManagedDashboard"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;
};

/**
 * Describes the message types.v1.DashboardStatus.ManagedDashboard.
 * Use `create(DashboardStatus_ManagedDashboardSchema)` to create a new message.
 */
export const DashboardStatus_ManagedDashboardSchema: GenMessage<DashboardStatus_ManagedDashboard> = /*@__PURE__*/
  messageDesc(file_types_v1_dashboard, 3, 0);

/**
 * @generated from message types.v1.DashboardStatus.GeneratedDashboard
 */
export type DashboardStatus_GeneratedDashboard = Message<"types.v1.DashboardStatus.GeneratedDashboard"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * @generated from field: string detection_reason = 2;
   */
  detectionReason: string;
};

/**
 * Describes the message types.v1.DashboardStatus.GeneratedDashboard.
 * Use `create(DashboardStatus_GeneratedDashboardSchema)` to create a new message.
 */
export const DashboardStatus_GeneratedDashboardSchema: GenMessage<DashboardStatus_GeneratedDashboard> = /*@__PURE__*/
  messageDesc(file_types_v1_dashboard, 3, 1);

/**
 * @generated from message types.v1.DashboardStatus.BuiltinDashboard
 */
export type DashboardStatus_BuiltinDashboard = Message<"types.v1.DashboardStatus.BuiltinDashboard"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message types.v1.DashboardStatus.BuiltinDashboard.
 * Use `create(DashboardStatus_BuiltinDashboardSchema)` to create a new message.
 */
export const DashboardStatus_BuiltinDashboardSchema: GenMessage<DashboardStatus_BuiltinDashboard> = /*@__PURE__*/
  messageDesc(file_types_v1_dashboard, 3, 2);

/**
 * @generated from message types.v1.DashboardStatus.RemoteDashboard
 */
export type DashboardStatus_RemoteDashboard = Message<"types.v1.DashboardStatus.RemoteDashboard"> & {
  /**
   * @generated from field: string repository_url = 1;
   */
  repositoryUrl: string;

  /**
   * @generated from field: string path = 2;
   */
  path: string;

  /**
   * @generated from field: string ref = 3;
   */
  ref: string;
};

/**
 * Describes the message types.v1.DashboardStatus.RemoteDashboard.
 * Use `create(DashboardStatus_RemoteDashboardSchema)` to create a new message.
 */
export const DashboardStatus_RemoteDashboardSchema: GenMessage<DashboardStatus_RemoteDashboard> = /*@__PURE__*/
  messageDesc(file_types_v1_dashboard, 3, 3);

