// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/database.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Val } from "./types_pb";
import { file_types_v1_types } from "./types_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/database.proto.
 */
export const file_types_v1_database: GenFile = /*@__PURE__*/
  fileDesc("Chd0eXBlcy92MS9kYXRhYmFzZS5wcm90bxIIdHlwZXMudjEi9AEKC1NpZ25hbFN0YXRzEg0KBWNvdW50GAEgASgEEjAKDG9sZGVzdF9lbnRyeRgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASMgoOeW91bmdlc3RfZW50cnkYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEh8KEnN0b3JhZ2Vfc2l6ZV9ieXRlcxgEIAEoBEgAiAEBEiAKE2luZ2VzdGVkX3NpemVfYnl0ZXMYBSABKARIAYgBAUIVChNfc3RvcmFnZV9zaXplX2J5dGVzQhYKFF9pbmdlc3RlZF9zaXplX2J5dGVzIqABCg1EYXRhYmFzZVN0YXRzEiMKBGxvZ3MYASABKAsyFS50eXBlcy52MS5TaWduYWxTdGF0cxIkCgVzcGFucxgCIAEoCzIVLnR5cGVzLnYxLlNpZ25hbFN0YXRzEiYKB21ldHJpY3MYAyABKAsyFS50eXBlcy52MS5TaWduYWxTdGF0cxIcCgVleHRyYRgKIAEoCzINLnR5cGVzLnYxLlZhbEKLAQoMY29tLnR5cGVzLnYxQg1EYXRhYmFzZVByb3RvUAFaK2dpdGh1Yi5jb20vbWluaXRhcGUvYXBpL2dvL3R5cGVzL3YxO3R5cGVzdjGiAgNUWFiqAghUeXBlcy5WMcoCCFR5cGVzXFYx4gIUVHlwZXNcVjFcR1BCTWV0YWRhdGHqAglUeXBlczo6VjFiBnByb3RvMw", [file_google_protobuf_timestamp, file_types_v1_types]);

/**
 * @generated from message types.v1.SignalStats
 */
export type SignalStats = Message<"types.v1.SignalStats"> & {
  /**
   * @generated from field: uint64 count = 1;
   */
  count: bigint;

  /**
   * @generated from field: google.protobuf.Timestamp oldest_entry = 2;
   */
  oldestEntry?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp youngest_entry = 3;
   */
  youngestEntry?: Timestamp;

  /**
   * @generated from field: optional uint64 storage_size_bytes = 4;
   */
  storageSizeBytes?: bigint;

  /**
   * @generated from field: optional uint64 ingested_size_bytes = 5;
   */
  ingestedSizeBytes?: bigint;
};

/**
 * Describes the message types.v1.SignalStats.
 * Use `create(SignalStatsSchema)` to create a new message.
 */
export const SignalStatsSchema: GenMessage<SignalStats> = /*@__PURE__*/
  messageDesc(file_types_v1_database, 0);

/**
 * @generated from message types.v1.DatabaseStats
 */
export type DatabaseStats = Message<"types.v1.DatabaseStats"> & {
  /**
   * @generated from field: types.v1.SignalStats logs = 1;
   */
  logs?: SignalStats;

  /**
   * @generated from field: types.v1.SignalStats spans = 2;
   */
  spans?: SignalStats;

  /**
   * @generated from field: types.v1.SignalStats metrics = 3;
   */
  metrics?: SignalStats;

  /**
   * @generated from field: types.v1.Val extra = 10;
   */
  extra?: Val;
};

/**
 * Describes the message types.v1.DatabaseStats.
 * Use `create(DatabaseStatsSchema)` to create a new message.
 */
export const DatabaseStatsSchema: GenMessage<DatabaseStats> = /*@__PURE__*/
  messageDesc(file_types_v1_database, 1);

