// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/environment_token.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/environment_token.proto.
 */
export const file_types_v1_environment_token: GenFile = /*@__PURE__*/
  fileDesc("CiB0eXBlcy92MS9lbnZpcm9ubWVudF90b2tlbi5wcm90bxIIdHlwZXMudjEihwIKEEVudmlyb25tZW50VG9rZW4SFgoOZW52aXJvbm1lbnRfaWQYASABKAMSEAoIdG9rZW5faWQYAiABKAMSDQoFdG9rZW4YAyABKAkSKAoFcm9sZXMYBCADKA4yGS50eXBlcy52MS5FbnZpcm9ubWVudFJvbGUSLgoKZXhwaXJlc19hdBgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKcmV2b2tlZF9hdBgGIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASMAoMbGFzdF91c2VkX2F0GAcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCpMCg9FbnZpcm9ubWVudFJvbGUSGwoXRW52aXJvbm1lbnRSb2xlX0ludmFsaWQQABIcChhFbnZpcm9ubWVudFJvbGVfSW5nZXN0b3IQAUKTAQoMY29tLnR5cGVzLnYxQhVFbnZpcm9ubWVudFRva2VuUHJvdG9QAVorZ2l0aHViLmNvbS9taW5pdGFwZS9hcGkvZ28vdHlwZXMvdjE7dHlwZXN2MaICA1RYWKoCCFR5cGVzLlYxygIIVHlwZXNcVjHiAhRUeXBlc1xWMVxHUEJNZXRhZGF0YeoCCVR5cGVzOjpWMWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message types.v1.EnvironmentToken
 */
export type EnvironmentToken = Message<"types.v1.EnvironmentToken"> & {
  /**
   * @generated from field: int64 environment_id = 1;
   */
  environmentId: bigint;

  /**
   * @generated from field: int64 token_id = 2;
   */
  tokenId: bigint;

  /**
   * @generated from field: string token = 3;
   */
  token: string;

  /**
   * @generated from field: repeated types.v1.EnvironmentRole roles = 4;
   */
  roles: EnvironmentRole[];

  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 5;
   */
  expiresAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp revoked_at = 6;
   */
  revokedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp last_used_at = 7;
   */
  lastUsedAt?: Timestamp;
};

/**
 * Describes the message types.v1.EnvironmentToken.
 * Use `create(EnvironmentTokenSchema)` to create a new message.
 */
export const EnvironmentTokenSchema: GenMessage<EnvironmentToken> = /*@__PURE__*/
  messageDesc(file_types_v1_environment_token, 0);

/**
 * @generated from enum types.v1.EnvironmentRole
 */
export enum EnvironmentRole {
  /**
   * @generated from enum value: EnvironmentRole_Invalid = 0;
   */
  EnvironmentRole_Invalid = 0,

  /**
   * @generated from enum value: EnvironmentRole_Ingestor = 1;
   */
  EnvironmentRole_Ingestor = 1,
}

/**
 * Describes the enum types.v1.EnvironmentRole.
 */
export const EnvironmentRoleSchema: GenEnum<EnvironmentRole> = /*@__PURE__*/
  enumDesc(file_types_v1_environment_token, 0);

