// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/favorite_query.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Query } from "./query_pb";
import { file_types_v1_query } from "./query_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/favorite_query.proto.
 */
export const file_types_v1_favorite_query: GenFile = /*@__PURE__*/
  fileDesc("Ch10eXBlcy92MS9mYXZvcml0ZV9xdWVyeS5wcm90bxIIdHlwZXMudjEiygEKDUZhdm9yaXRlUXVlcnkSCgoCaWQYASABKAMSDAoEbmFtZRgCIAEoCRIRCglyYXdfcXVlcnkYAyABKAkSHgoFcXVlcnkYBCABKAsyDy50eXBlcy52MS5RdWVyeRIMCgRub3RlGAUgASgJEi4KCmNyZWF0ZWRfYXQYBiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnVwZGF0ZWRfYXQYByABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQpABCgxjb20udHlwZXMudjFCEkZhdm9yaXRlUXVlcnlQcm90b1ABWitnaXRodWIuY29tL21pbml0YXBlL2FwaS9nby90eXBlcy92MTt0eXBlc3YxogIDVFhYqgIIVHlwZXMuVjHKAghUeXBlc1xWMeICFFR5cGVzXFYxXEdQQk1ldGFkYXRh6gIJVHlwZXM6OlYxYgZwcm90bzM", [file_google_protobuf_timestamp, file_types_v1_query]);

/**
 * @generated from message types.v1.FavoriteQuery
 */
export type FavoriteQuery = Message<"types.v1.FavoriteQuery"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string raw_query = 3;
   */
  rawQuery: string;

  /**
   * @generated from field: types.v1.Query query = 4;
   */
  query?: Query;

  /**
   * @generated from field: string note = 5;
   */
  note: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 7;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message types.v1.FavoriteQuery.
 * Use `create(FavoriteQuerySchema)` to create a new message.
 */
export const FavoriteQuerySchema: GenMessage<FavoriteQuery> = /*@__PURE__*/
  messageDesc(file_types_v1_favorite_query, 0);

