// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/feature.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_types_v1_price } from "./price_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/feature.proto.
 */
export const file_types_v1_feature: GenFile = /*@__PURE__*/
  fileDesc("ChZ0eXBlcy92MS9mZWF0dXJlLnByb3RvEgh0eXBlcy52MSIXCgdGZWF0dXJlEgwKBG5hbWUYASABKAlCigEKDGNvbS50eXBlcy52MUIMRmVhdHVyZVByb3RvUAFaK2dpdGh1Yi5jb20vbWluaXRhcGUvYXBpL2dvL3R5cGVzL3YxO3R5cGVzdjGiAgNUWFiqAghUeXBlcy5WMcoCCFR5cGVzXFYx4gIUVHlwZXNcVjFcR1BCTWV0YWRhdGHqAglUeXBlczo6VjFiBnByb3RvMw", [file_google_protobuf_timestamp, file_types_v1_price]);

/**
 * @generated from message types.v1.Feature
 */
export type Feature = Message<"types.v1.Feature"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message types.v1.Feature.
 * Use `create(FeatureSchema)` to create a new message.
 */
export const FeatureSchema: GenMessage<Feature> = /*@__PURE__*/
  messageDesc(file_types_v1_feature, 0);

