// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/machine.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/machine.proto.
 */
export const file_types_v1_machine: GenFile = /*@__PURE__*/
  fileDesc("ChZ0eXBlcy92MS9tYWNoaW5lLnByb3RvEgh0eXBlcy52MSJTCgdNYWNoaW5lEgoKAmlkGAEgASgDEgwKBG5hbWUYAiABKAkSGAoQb3BlcmF0aW5nX3N5c3RlbRgDIAEoCRIUCgxhcmNoaXRlY3R1cmUYBCABKAlCigEKDGNvbS50eXBlcy52MUIMTWFjaGluZVByb3RvUAFaK2dpdGh1Yi5jb20vbWluaXRhcGUvYXBpL2dvL3R5cGVzL3YxO3R5cGVzdjGiAgNUWFiqAghUeXBlcy5WMcoCCFR5cGVzXFYx4gIUVHlwZXNcVjFcR1BCTWV0YWRhdGHqAglUeXBlczo6VjFiBnByb3RvMw");

/**
 * @generated from message types.v1.Machine
 */
export type Machine = Message<"types.v1.Machine"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string operating_system = 3;
   */
  operatingSystem: string;

  /**
   * @generated from field: string architecture = 4;
   */
  architecture: string;
};

/**
 * Describes the message types.v1.Machine.
 * Use `create(MachineSchema)` to create a new message.
 */
export const MachineSchema: GenMessage<Machine> = /*@__PURE__*/
  messageDesc(file_types_v1_machine, 0);

