// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/meta.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/meta.proto.
 */
export const file_types_v1_meta: GenFile = /*@__PURE__*/
  fileDesc("ChN0eXBlcy92MS9tZXRhLnByb3RvEgh0eXBlcy52MSIjCgdSZXFNZXRhEhIKCm1hY2hpbmVfaWQYAiABKANKBAgBEAIiIwoHUmVzTWV0YRISCgptYWNoaW5lX2lkGAIgASgDSgQIARACQocBCgxjb20udHlwZXMudjFCCU1ldGFQcm90b1ABWitnaXRodWIuY29tL21pbml0YXBlL2FwaS9nby90eXBlcy92MTt0eXBlc3YxogIDVFhYqgIIVHlwZXMuVjHKAghUeXBlc1xWMeICFFR5cGVzXFYxXEdQQk1ldGFkYXRh6gIJVHlwZXM6OlYxYgZwcm90bzM");

/**
 * @generated from message types.v1.ReqMeta
 */
export type ReqMeta = Message<"types.v1.ReqMeta"> & {
  /**
   * @generated from field: int64 machine_id = 2;
   */
  machineId: bigint;
};

/**
 * Describes the message types.v1.ReqMeta.
 * Use `create(ReqMetaSchema)` to create a new message.
 */
export const ReqMetaSchema: GenMessage<ReqMeta> = /*@__PURE__*/
  messageDesc(file_types_v1_meta, 0);

/**
 * @generated from message types.v1.ResMeta
 */
export type ResMeta = Message<"types.v1.ResMeta"> & {
  /**
   * @generated from field: int64 machine_id = 2;
   */
  machineId: bigint;
};

/**
 * Describes the message types.v1.ResMeta.
 * Use `create(ResMetaSchema)` to create a new message.
 */
export const ResMetaSchema: GenMessage<ResMeta> = /*@__PURE__*/
  messageDesc(file_types_v1_meta, 1);

