// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/organization.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { PublicUser } from "./user_pb";
import { file_types_v1_user } from "./user_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/organization.proto.
 */
export const file_types_v1_organization: GenFile = /*@__PURE__*/
  fileDesc("Cht0eXBlcy92MS9vcmdhbml6YXRpb24ucHJvdG8SCHR5cGVzLnYxIq0BCgxPcmdhbml6YXRpb24SCgoCaWQYASABKAMSMwoEbmFtZRgCIAEoCUIlukgiciAQAxgnMhpeW2EtekEtWjAtOV1bYS16QS1aMC05LV0rJBIMCgRzbHVnGAMgASgJEgwKBGxvZ28YBCABKAkSEAoIbWV0YWRhdGEYBSABKAkSLgoKY3JlYXRlZF9hdBgHIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAilQIKCkludml0YXRpb24SCgoCaWQYASABKAMSKAoKaW52aXRlZF9ieRgCIAEoCzIULnR5cGVzLnYxLlB1YmxpY1VzZXISGgoSaW52aXRlZF91c2VyX2VtYWlsGAMgASgJEikKBXN0YXRlGAQgASgOMhoudHlwZXMudjEuSW52aXRhdGlvbi5TdGF0ZRIMCgRyb2xlGAUgASgJEi8KCmV4cGlyZXNfYXQY9wMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCJLCgVTdGF0ZRINCglVTkRFRklORUQQABILCgdQRU5ESU5HEAESDAoIQUNDRVBURUQQAhILCgdSRVZPS0VEEAMSCwoHRVhQSVJFRBAEQo8BCgxjb20udHlwZXMudjFCEU9yZ2FuaXphdGlvblByb3RvUAFaK2dpdGh1Yi5jb20vbWluaXRhcGUvYXBpL2dvL3R5cGVzL3YxO3R5cGVzdjGiAgNUWFiqAghUeXBlcy5WMcoCCFR5cGVzXFYx4gIUVHlwZXNcVjFcR1BCTWV0YWRhdGHqAglUeXBlczo6VjFiBnByb3RvMw", [file_buf_validate_validate, file_google_protobuf_timestamp, file_types_v1_user]);

/**
 * @generated from message types.v1.Organization
 */
export type Organization = Message<"types.v1.Organization"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * unique URL slug from better-auth
   *
   * @generated from field: string slug = 3;
   */
  slug: string;

  /**
   * logo URL from better-auth
   *
   * @generated from field: string logo = 4;
   */
  logo: string;

  /**
   * JSON metadata from better-auth
   *
   * @generated from field: string metadata = 5;
   */
  metadata: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 7;
   */
  createdAt?: Timestamp;
};

/**
 * Describes the message types.v1.Organization.
 * Use `create(OrganizationSchema)` to create a new message.
 */
export const OrganizationSchema: GenMessage<Organization> = /*@__PURE__*/
  messageDesc(file_types_v1_organization, 0);

/**
 * @generated from message types.v1.Invitation
 */
export type Invitation = Message<"types.v1.Invitation"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: types.v1.PublicUser invited_by = 2;
   */
  invitedBy?: PublicUser;

  /**
   * @generated from field: string invited_user_email = 3;
   */
  invitedUserEmail: string;

  /**
   * @generated from field: types.v1.Invitation.State state = 4;
   */
  state: Invitation_State;

  /**
   * invitation role from better-auth
   *
   * @generated from field: string role = 5;
   */
  role: string;

  /**
   * only timestamp better-auth tracks
   *
   * @generated from field: google.protobuf.Timestamp expires_at = 503;
   */
  expiresAt?: Timestamp;
};

/**
 * Describes the message types.v1.Invitation.
 * Use `create(InvitationSchema)` to create a new message.
 */
export const InvitationSchema: GenMessage<Invitation> = /*@__PURE__*/
  messageDesc(file_types_v1_organization, 1);

/**
 * @generated from enum types.v1.Invitation.State
 */
export enum Invitation_State {
  /**
   * @generated from enum value: UNDEFINED = 0;
   */
  UNDEFINED = 0,

  /**
   * @generated from enum value: PENDING = 1;
   */
  PENDING = 1,

  /**
   * @generated from enum value: ACCEPTED = 2;
   */
  ACCEPTED = 2,

  /**
   * @generated from enum value: REVOKED = 3;
   */
  REVOKED = 3,

  /**
   * @generated from enum value: EXPIRED = 4;
   */
  EXPIRED = 4,
}

/**
 * Describes the enum types.v1.Invitation.State.
 */
export const Invitation_StateSchema: GenEnum<Invitation_State> = /*@__PURE__*/
  enumDesc(file_types_v1_organization, 1, 0);

