// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/otel_tracing.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Duration, Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_duration, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Resource } from "./otel_resource_pb";
import { file_types_v1_otel_resource } from "./otel_resource_pb";
import type { Scope } from "./otel_scope_pb";
import { file_types_v1_otel_scope } from "./otel_scope_pb";
import type { KV, SpanID, TraceID } from "./types_pb";
import { file_types_v1_types } from "./types_pb";
import type { ULID } from "./ulid_pb";
import { file_types_v1_ulid } from "./ulid_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/otel_tracing.proto.
 */
export const file_types_v1_otel_tracing: GenFile = /*@__PURE__*/
  fileDesc("Cht0eXBlcy92MS9vdGVsX3RyYWNpbmcucHJvdG8SCHR5cGVzLnYxIksKBVRyYWNlEiMKCHRyYWNlX2lkGAEgASgLMhEudHlwZXMudjEuVHJhY2VJRBIdCgVzcGFucxgCIAMoCzIOLnR5cGVzLnYxLlNwYW4inwgKBFNwYW4SHAoEdWxpZBhkIAEoCzIOLnR5cGVzLnYxLlVMSUQSLQoJaW5kZXh0aW1lGGUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIjCgh0cmFjZV9pZBgBIAEoCzIRLnR5cGVzLnYxLlRyYWNlSUQSIQoHc3Bhbl9pZBgCIAEoCzIQLnR5cGVzLnYxLlNwYW5JRBITCgt0cmFjZV9zdGF0ZRgDIAEoCRIoCg5wYXJlbnRfc3Bhbl9pZBgEIAEoCzIQLnR5cGVzLnYxLlNwYW5JRBINCgVmbGFncxgFIAEoDRIMCgRuYW1lGAYgASgJEiUKBGtpbmQYByABKA4yFy50eXBlcy52MS5TcGFuLlNwYW5LaW5kEhQKDHNlcnZpY2VfbmFtZRgIIAEoCRIoCgR0aW1lGAkgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIrCghkdXJhdGlvbhgKIAEoCzIZLmdvb2dsZS5wcm90b2J1Zi5EdXJhdGlvbhIkCghyZXNvdXJjZRgLIAEoCzISLnR5cGVzLnYxLlJlc291cmNlEh4KBXNjb3BlGAwgASgLMg8udHlwZXMudjEuU2NvcGUSIAoKYXR0cmlidXRlcxgNIAMoCzIMLnR5cGVzLnYxLktWEiQKBmV2ZW50cxgOIAMoCzIULnR5cGVzLnYxLlNwYW4uRXZlbnQSIgoFbGlua3MYDyADKAsyEy50eXBlcy52MS5TcGFuLkxpbmsSJQoGc3RhdHVzGBAgASgLMhUudHlwZXMudjEuU3Bhbi5TdGF0dXMaXwoFRXZlbnQSLQoJdGltZXN0YW1wGAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIMCgRuYW1lGAIgASgJEhkKA2t2cxgDIAMoCzIMLnR5cGVzLnYxLktWGo0BCgRMaW5rEiMKCHRyYWNlX2lkGAEgASgLMhEudHlwZXMudjEuVHJhY2VJRBIhCgdzcGFuX2lkGAIgASgLMhAudHlwZXMudjEuU3BhbklEEhMKC3RyYWNlX3N0YXRlGAMgASgJEhkKA2t2cxgEIAMoCzIMLnR5cGVzLnYxLktWEg0KBWZsYWdzGAUgASgNGmkKBlN0YXR1cxIPCgdtZXNzYWdlGAEgASgJEigKBGNvZGUYAiABKA4yGi50eXBlcy52MS5TcGFuLlN0YXR1cy5Db2RlIiQKBENvZGUSCQoFVU5TRVQQABIGCgJPSxABEgkKBUVSUk9SEAIiXQoIU3BhbktpbmQSDwoLVU5TUEVDSUZJRUQQABIMCghJTlRFUk5BTBABEgoKBlNFUlZFUhACEgoKBkNMSUVOVBADEgwKCFBST0RVQ0VSEAQSDAoIQ09OU1VNRVIQBUKOAQoMY29tLnR5cGVzLnYxQhBPdGVsVHJhY2luZ1Byb3RvUAFaK2dpdGh1Yi5jb20vbWluaXRhcGUvYXBpL2dvL3R5cGVzL3YxO3R5cGVzdjGiAgNUWFiqAghUeXBlcy5WMcoCCFR5cGVzXFYx4gIUVHlwZXNcVjFcR1BCTWV0YWRhdGHqAglUeXBlczo6VjFiBnByb3RvMw", [file_google_protobuf_duration, file_google_protobuf_timestamp, file_types_v1_otel_resource, file_types_v1_otel_scope, file_types_v1_types, file_types_v1_ulid]);

/**
 * @generated from message types.v1.Trace
 */
export type Trace = Message<"types.v1.Trace"> & {
  /**
   * @generated from field: types.v1.TraceID trace_id = 1;
   */
  traceId?: TraceID;

  /**
   * @generated from field: repeated types.v1.Span spans = 2;
   */
  spans: Span[];
};

/**
 * Describes the message types.v1.Trace.
 * Use `create(TraceSchema)` to create a new message.
 */
export const TraceSchema: GenMessage<Trace> = /*@__PURE__*/
  messageDesc(file_types_v1_otel_tracing, 0);

/**
 * @generated from message types.v1.Span
 */
export type Span = Message<"types.v1.Span"> & {
  /**
   * @generated from field: types.v1.ULID ulid = 100;
   */
  ulid?: ULID;

  /**
   * @generated from field: google.protobuf.Timestamp indextime = 101;
   */
  indextime?: Timestamp;

  /**
   * @generated from field: types.v1.TraceID trace_id = 1;
   */
  traceId?: TraceID;

  /**
   * @generated from field: types.v1.SpanID span_id = 2;
   */
  spanId?: SpanID;

  /**
   * @generated from field: string trace_state = 3;
   */
  traceState: string;

  /**
   * @generated from field: types.v1.SpanID parent_span_id = 4;
   */
  parentSpanId?: SpanID;

  /**
   * @generated from field: uint32 flags = 5;
   */
  flags: number;

  /**
   * @generated from field: string name = 6;
   */
  name: string;

  /**
   * @generated from field: types.v1.Span.SpanKind kind = 7;
   */
  kind: Span_SpanKind;

  /**
   * @generated from field: string service_name = 8;
   */
  serviceName: string;

  /**
   * @generated from field: google.protobuf.Timestamp time = 9;
   */
  time?: Timestamp;

  /**
   * @generated from field: google.protobuf.Duration duration = 10;
   */
  duration?: Duration;

  /**
   * @generated from field: types.v1.Resource resource = 11;
   */
  resource?: Resource;

  /**
   * @generated from field: types.v1.Scope scope = 12;
   */
  scope?: Scope;

  /**
   * @generated from field: repeated types.v1.KV attributes = 13;
   */
  attributes: KV[];

  /**
   * @generated from field: repeated types.v1.Span.Event events = 14;
   */
  events: Span_Event[];

  /**
   * @generated from field: repeated types.v1.Span.Link links = 15;
   */
  links: Span_Link[];

  /**
   * @generated from field: types.v1.Span.Status status = 16;
   */
  status?: Span_Status;
};

/**
 * Describes the message types.v1.Span.
 * Use `create(SpanSchema)` to create a new message.
 */
export const SpanSchema: GenMessage<Span> = /*@__PURE__*/
  messageDesc(file_types_v1_otel_tracing, 1);

/**
 * @generated from message types.v1.Span.Event
 */
export type Span_Event = Message<"types.v1.Span.Event"> & {
  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 1;
   */
  timestamp?: Timestamp;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: repeated types.v1.KV kvs = 3;
   */
  kvs: KV[];
};

/**
 * Describes the message types.v1.Span.Event.
 * Use `create(Span_EventSchema)` to create a new message.
 */
export const Span_EventSchema: GenMessage<Span_Event> = /*@__PURE__*/
  messageDesc(file_types_v1_otel_tracing, 1, 0);

/**
 * @generated from message types.v1.Span.Link
 */
export type Span_Link = Message<"types.v1.Span.Link"> & {
  /**
   * @generated from field: types.v1.TraceID trace_id = 1;
   */
  traceId?: TraceID;

  /**
   * @generated from field: types.v1.SpanID span_id = 2;
   */
  spanId?: SpanID;

  /**
   * @generated from field: string trace_state = 3;
   */
  traceState: string;

  /**
   * @generated from field: repeated types.v1.KV kvs = 4;
   */
  kvs: KV[];

  /**
   * @generated from field: uint32 flags = 5;
   */
  flags: number;
};

/**
 * Describes the message types.v1.Span.Link.
 * Use `create(Span_LinkSchema)` to create a new message.
 */
export const Span_LinkSchema: GenMessage<Span_Link> = /*@__PURE__*/
  messageDesc(file_types_v1_otel_tracing, 1, 1);

/**
 * @generated from message types.v1.Span.Status
 */
export type Span_Status = Message<"types.v1.Span.Status"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  /**
   * @generated from field: types.v1.Span.Status.Code code = 2;
   */
  code: Span_Status_Code;
};

/**
 * Describes the message types.v1.Span.Status.
 * Use `create(Span_StatusSchema)` to create a new message.
 */
export const Span_StatusSchema: GenMessage<Span_Status> = /*@__PURE__*/
  messageDesc(file_types_v1_otel_tracing, 1, 2);

/**
 * @generated from enum types.v1.Span.Status.Code
 */
export enum Span_Status_Code {
  /**
   * @generated from enum value: UNSET = 0;
   */
  UNSET = 0,

  /**
   * @generated from enum value: OK = 1;
   */
  OK = 1,

  /**
   * @generated from enum value: ERROR = 2;
   */
  ERROR = 2,
}

/**
 * Describes the enum types.v1.Span.Status.Code.
 */
export const Span_Status_CodeSchema: GenEnum<Span_Status_Code> = /*@__PURE__*/
  enumDesc(file_types_v1_otel_tracing, 1, 2, 0);

/**
 * @generated from enum types.v1.Span.SpanKind
 */
export enum Span_SpanKind {
  /**
   * @generated from enum value: UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: INTERNAL = 1;
   */
  INTERNAL = 1,

  /**
   * @generated from enum value: SERVER = 2;
   */
  SERVER = 2,

  /**
   * @generated from enum value: CLIENT = 3;
   */
  CLIENT = 3,

  /**
   * @generated from enum value: PRODUCER = 4;
   */
  PRODUCER = 4,

  /**
   * @generated from enum value: CONSUMER = 5;
   */
  CONSUMER = 5,
}

/**
 * Describes the enum types.v1.Span.SpanKind.
 */
export const Span_SpanKindSchema: GenEnum<Span_SpanKind> = /*@__PURE__*/
  enumDesc(file_types_v1_otel_tracing, 1, 0);

