// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/otel_logging.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Resource } from "./otel_resource_pb";
import { file_types_v1_otel_resource } from "./otel_resource_pb";
import type { Scope } from "./otel_scope_pb";
import { file_types_v1_otel_scope } from "./otel_scope_pb";
import { file_types_v1_otel_tracing } from "./otel_tracing_pb";
import type { KV, SpanID, TraceID } from "./types_pb";
import { file_types_v1_types } from "./types_pb";
import type { ULID } from "./ulid_pb";
import { file_types_v1_ulid } from "./ulid_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/otel_logging.proto.
 */
export const file_types_v1_otel_logging: GenFile = /*@__PURE__*/
  fileDesc("Cht0eXBlcy92MS9vdGVsX2xvZ2dpbmcucHJvdG8SCHR5cGVzLnYxItMDCgNMb2cSHAoEdWxpZBhkIAEoCzIOLnR5cGVzLnYxLlVMSUQSNgoSb2JzZXJ2ZWRfdGltZXN0YW1wGGUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBILCgNyYXcYZiABKAwSLQoJdGltZXN0YW1wGAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIoCgh0cmFjZV9pZBgDIAEoCzIRLnR5cGVzLnYxLlRyYWNlSURIAIgBARImCgdzcGFuX2lkGAQgASgLMhAudHlwZXMudjEuU3BhbklESAGIAQESEwoLdHJhY2VfZmxhZ3MYBSABKA0SFQoNc2V2ZXJpdHlfdGV4dBgGIAEoCRIXCg9zZXZlcml0eV9udW1iZXIYByABKA0SFAoMc2VydmljZV9uYW1lGAggASgJEgwKBGJvZHkYCSABKAkSJAoIcmVzb3VyY2UYCiABKAsyEi50eXBlcy52MS5SZXNvdXJjZRIeCgVzY29wZRgLIAEoCzIPLnR5cGVzLnYxLlNjb3BlEiAKCmF0dHJpYnV0ZXMYFiADKAsyDC50eXBlcy52MS5LVkILCglfdHJhY2VfaWRCCgoIX3NwYW5faWRCjgEKDGNvbS50eXBlcy52MUIQT3RlbExvZ2dpbmdQcm90b1ABWitnaXRodWIuY29tL21pbml0YXBlL2FwaS9nby90eXBlcy92MTt0eXBlc3YxogIDVFhYqgIIVHlwZXMuVjHKAghUeXBlc1xWMeICFFR5cGVzXFYxXEdQQk1ldGFkYXRh6gIJVHlwZXM6OlYxYgZwcm90bzM", [file_google_protobuf_timestamp, file_types_v1_otel_resource, file_types_v1_otel_scope, file_types_v1_otel_tracing, file_types_v1_types, file_types_v1_ulid]);

/**
 * @generated from message types.v1.Log
 */
export type Log = Message<"types.v1.Log"> & {
  /**
   * @generated from field: types.v1.ULID ulid = 100;
   */
  ulid?: ULID;

  /**
   * @generated from field: google.protobuf.Timestamp observed_timestamp = 101;
   */
  observedTimestamp?: Timestamp;

  /**
   * @generated from field: bytes raw = 102;
   */
  raw: Uint8Array;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 2;
   */
  timestamp?: Timestamp;

  /**
   * @generated from field: optional types.v1.TraceID trace_id = 3;
   */
  traceId?: TraceID;

  /**
   * @generated from field: optional types.v1.SpanID span_id = 4;
   */
  spanId?: SpanID;

  /**
   * @generated from field: uint32 trace_flags = 5;
   */
  traceFlags: number;

  /**
   * @generated from field: string severity_text = 6;
   */
  severityText: string;

  /**
   * @generated from field: uint32 severity_number = 7;
   */
  severityNumber: number;

  /**
   * @generated from field: string service_name = 8;
   */
  serviceName: string;

  /**
   * @generated from field: string body = 9;
   */
  body: string;

  /**
   * @generated from field: types.v1.Resource resource = 10;
   */
  resource?: Resource;

  /**
   * @generated from field: types.v1.Scope scope = 11;
   */
  scope?: Scope;

  /**
   * @generated from field: repeated types.v1.KV attributes = 22;
   */
  attributes: KV[];
};

/**
 * Describes the message types.v1.Log.
 * Use `create(LogSchema)` to create a new message.
 */
export const LogSchema: GenMessage<Log> = /*@__PURE__*/
  messageDesc(file_types_v1_otel_logging, 0);

