// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/otel_scope.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { KV } from "./types_pb";
import { file_types_v1_types } from "./types_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/otel_scope.proto.
 */
export const file_types_v1_otel_scope: GenFile = /*@__PURE__*/
  fileDesc("Chl0eXBlcy92MS9vdGVsX3Njb3BlLnByb3RvEgh0eXBlcy52MSJzCgVTY29wZRIVCg1zY29wZV9oYXNoXzY0GAEgASgEEhIKCnNjaGVtYV91cmwYAiABKAkSDAoEbmFtZRgDIAEoCRIPCgd2ZXJzaW9uGAQgASgJEiAKCmF0dHJpYnV0ZXMYBSADKAsyDC50eXBlcy52MS5LVkKMAQoMY29tLnR5cGVzLnYxQg5PdGVsU2NvcGVQcm90b1ABWitnaXRodWIuY29tL21pbml0YXBlL2FwaS9nby90eXBlcy92MTt0eXBlc3YxogIDVFhYqgIIVHlwZXMuVjHKAghUeXBlc1xWMeICFFR5cGVzXFYxXEdQQk1ldGFkYXRh6gIJVHlwZXM6OlYxYgZwcm90bzM", [file_types_v1_types]);

/**
 * @generated from message types.v1.Scope
 */
export type Scope = Message<"types.v1.Scope"> & {
  /**
   * @generated from field: uint64 scope_hash_64 = 1;
   */
  scopeHash64: bigint;

  /**
   * @generated from field: string schema_url = 2;
   */
  schemaUrl: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string version = 4;
   */
  version: string;

  /**
   * @generated from field: repeated types.v1.KV attributes = 5;
   */
  attributes: KV[];
};

/**
 * Describes the message types.v1.Scope.
 * Use `create(ScopeSchema)` to create a new message.
 */
export const ScopeSchema: GenMessage<Scope> = /*@__PURE__*/
  messageDesc(file_types_v1_otel_scope, 0);

