// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/otel_resource.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { KV } from "./types_pb";
import { file_types_v1_types } from "./types_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/otel_resource.proto.
 */
export const file_types_v1_otel_resource: GenFile = /*@__PURE__*/
  fileDesc("Chx0eXBlcy92MS9vdGVsX3Jlc291cmNlLnByb3RvEgh0eXBlcy52MSJaCghSZXNvdXJjZRIYChByZXNvdXJjZV9oYXNoXzY0GAEgASgEEhIKCnNjaGVtYV91cmwYAiABKAkSIAoKYXR0cmlidXRlcxgDIAMoCzIMLnR5cGVzLnYxLktWQo8BCgxjb20udHlwZXMudjFCEU90ZWxSZXNvdXJjZVByb3RvUAFaK2dpdGh1Yi5jb20vbWluaXRhcGUvYXBpL2dvL3R5cGVzL3YxO3R5cGVzdjGiAgNUWFiqAghUeXBlcy5WMcoCCFR5cGVzXFYx4gIUVHlwZXNcVjFcR1BCTWV0YWRhdGHqAglUeXBlczo6VjFiBnByb3RvMw", [file_types_v1_types]);

/**
 * @generated from message types.v1.Resource
 */
export type Resource = Message<"types.v1.Resource"> & {
  /**
   * @generated from field: uint64 resource_hash_64 = 1;
   */
  resourceHash64: bigint;

  /**
   * @generated from field: string schema_url = 2;
   */
  schemaUrl: string;

  /**
   * @generated from field: repeated types.v1.KV attributes = 3;
   */
  attributes: KV[];
};

/**
 * Describes the message types.v1.Resource.
 * Use `create(ResourceSchema)` to create a new message.
 */
export const ResourceSchema: GenMessage<Resource> = /*@__PURE__*/
  messageDesc(file_types_v1_otel_resource, 0);

