// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/payment_method.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/payment_method.proto.
 */
export const file_types_v1_payment_method: GenFile = /*@__PURE__*/
  fileDesc("Ch10eXBlcy92MS9wYXltZW50X21ldGhvZC5wcm90bxIIdHlwZXMudjEiagoHQWRkcmVzcxIMCgRjaXR5GAEgASgJEg8KB2NvdW50cnkYAiABKAkSDQoFbGluZTEYAyABKAkSDQoFbGluZTIYBCABKAkSEwoLcG9zdGFsX2NvZGUYBSABKAkSDQoFc3RhdGUYBiABKAkisAQKDVBheW1lbnRNZXRob2QSLgoKY3JlYXRlZF9hdBhkIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASEQoJc3RyaXBlX2lkGAEgASgJEi0KBGNhcmQYyAEgASgLMhwudHlwZXMudjEuUGF5bWVudE1ldGhvZC5DYXJkSAASPwoPYmlsbGluZ19kZXRhaWxzGAMgASgLMiYudHlwZXMudjEuUGF5bWVudE1ldGhvZC5CaWxsaW5nRGV0YWlscxqBAgoEQ2FyZBIxCgVicmFuZBgBIAEoDjIiLnR5cGVzLnYxLlBheW1lbnRNZXRob2QuQ2FyZC5CcmFuZBIPCgdjb3VudHJ5GAIgASgJEhYKDmRpc3BsYXlfYnJhbmRoGAMgASgJEhEKCWV4cF9tb250aBgEIAEoAxIQCghleHBfeWVhchgFIAEoAxINCgVsYXN0NBgGIAEoCSJpCgVCcmFuZBILCgd1bmtub3duEAASCAoEYW1leBABEgoKBmRpbmVycxACEgwKCGRpc2NvdmVyEAMSBwoDamNiEAQSDgoKbWFzdGVyY2FyZBAFEgwKCHVuaW9ucGF5EAYSCAoEdmlzYRAHGmAKDkJpbGxpbmdEZXRhaWxzEiIKB2FkZHJlc3MYASABKAsyES50eXBlcy52MS5BZGRyZXNzEg0KBWVtYWlsGAIgASgJEgwKBG5hbWUYAyABKAkSDQoFcGhvbmUYBCABKAlCBgoEdHlwZUKQAQoMY29tLnR5cGVzLnYxQhJQYXltZW50TWV0aG9kUHJvdG9QAVorZ2l0aHViLmNvbS9taW5pdGFwZS9hcGkvZ28vdHlwZXMvdjE7dHlwZXN2MaICA1RYWKoCCFR5cGVzLlYxygIIVHlwZXNcVjHiAhRUeXBlc1xWMVxHUEJNZXRhZGF0YeoCCVR5cGVzOjpWMWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message types.v1.Address
 */
export type Address = Message<"types.v1.Address"> & {
  /**
   * @generated from field: string city = 1;
   */
  city: string;

  /**
   * @generated from field: string country = 2;
   */
  country: string;

  /**
   * @generated from field: string line1 = 3;
   */
  line1: string;

  /**
   * @generated from field: string line2 = 4;
   */
  line2: string;

  /**
   * @generated from field: string postal_code = 5;
   */
  postalCode: string;

  /**
   * @generated from field: string state = 6;
   */
  state: string;
};

/**
 * Describes the message types.v1.Address.
 * Use `create(AddressSchema)` to create a new message.
 */
export const AddressSchema: GenMessage<Address> = /*@__PURE__*/
  messageDesc(file_types_v1_payment_method, 0);

/**
 * @generated from message types.v1.PaymentMethod
 */
export type PaymentMethod = Message<"types.v1.PaymentMethod"> & {
  /**
   * @generated from field: google.protobuf.Timestamp created_at = 100;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: string stripe_id = 1;
   */
  stripeId: string;

  /**
   * @generated from oneof types.v1.PaymentMethod.type
   */
  type: {
    /**
     * @generated from field: types.v1.PaymentMethod.Card card = 200;
     */
    value: PaymentMethod_Card;
    case: "card";
  } | { case: undefined; value?: undefined };

  /**
   * @generated from field: types.v1.PaymentMethod.BillingDetails billing_details = 3;
   */
  billingDetails?: PaymentMethod_BillingDetails;
};

/**
 * Describes the message types.v1.PaymentMethod.
 * Use `create(PaymentMethodSchema)` to create a new message.
 */
export const PaymentMethodSchema: GenMessage<PaymentMethod> = /*@__PURE__*/
  messageDesc(file_types_v1_payment_method, 1);

/**
 * @generated from message types.v1.PaymentMethod.Card
 */
export type PaymentMethod_Card = Message<"types.v1.PaymentMethod.Card"> & {
  /**
   * @generated from field: types.v1.PaymentMethod.Card.Brand brand = 1;
   */
  brand: PaymentMethod_Card_Brand;

  /**
   * @generated from field: string country = 2;
   */
  country: string;

  /**
   * @generated from field: string display_brandh = 3;
   */
  displayBrandh: string;

  /**
   * @generated from field: int64 exp_month = 4;
   */
  expMonth: bigint;

  /**
   * @generated from field: int64 exp_year = 5;
   */
  expYear: bigint;

  /**
   * @generated from field: string last4 = 6;
   */
  last4: string;
};

/**
 * Describes the message types.v1.PaymentMethod.Card.
 * Use `create(PaymentMethod_CardSchema)` to create a new message.
 */
export const PaymentMethod_CardSchema: GenMessage<PaymentMethod_Card> = /*@__PURE__*/
  messageDesc(file_types_v1_payment_method, 1, 0);

/**
 * @generated from enum types.v1.PaymentMethod.Card.Brand
 */
export enum PaymentMethod_Card_Brand {
  /**
   * @generated from enum value: unknown = 0;
   */
  unknown = 0,

  /**
   * @generated from enum value: amex = 1;
   */
  amex = 1,

  /**
   * @generated from enum value: diners = 2;
   */
  diners = 2,

  /**
   * @generated from enum value: discover = 3;
   */
  discover = 3,

  /**
   * @generated from enum value: jcb = 4;
   */
  jcb = 4,

  /**
   * @generated from enum value: mastercard = 5;
   */
  mastercard = 5,

  /**
   * @generated from enum value: unionpay = 6;
   */
  unionpay = 6,

  /**
   * @generated from enum value: visa = 7;
   */
  visa = 7,
}

/**
 * Describes the enum types.v1.PaymentMethod.Card.Brand.
 */
export const PaymentMethod_Card_BrandSchema: GenEnum<PaymentMethod_Card_Brand> = /*@__PURE__*/
  enumDesc(file_types_v1_payment_method, 1, 0, 0);

/**
 * @generated from message types.v1.PaymentMethod.BillingDetails
 */
export type PaymentMethod_BillingDetails = Message<"types.v1.PaymentMethod.BillingDetails"> & {
  /**
   * @generated from field: types.v1.Address address = 1;
   */
  address?: Address;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string phone = 4;
   */
  phone: string;
};

/**
 * Describes the message types.v1.PaymentMethod.BillingDetails.
 * Use `create(PaymentMethod_BillingDetailsSchema)` to create a new message.
 */
export const PaymentMethod_BillingDetailsSchema: GenMessage<PaymentMethod_BillingDetails> = /*@__PURE__*/
  messageDesc(file_types_v1_payment_method, 1, 1);

