// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/project.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_duration, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/project.proto.
 */
export const file_types_v1_project: GenFile = /*@__PURE__*/
  fileDesc("ChZ0eXBlcy92MS9wcm9qZWN0LnByb3RvEgh0eXBlcy52MSJ8CgdQcm9qZWN0EiMKBG1ldGEYASABKAsyFS50eXBlcy52MS5Qcm9qZWN0TWV0YRIjCgRzcGVjGAIgASgLMhUudHlwZXMudjEuUHJvamVjdFNwZWMSJwoGc3RhdHVzGAMgASgLMhcudHlwZXMudjEuUHJvamVjdFN0YXR1cyIZCgtQcm9qZWN0TWV0YRIKCgJpZBgBIAEoCSJGCgtQcm9qZWN0U3BlYxIMCgRuYW1lGAEgASgJEikKB3BvaW50ZXIYAiABKAsyGC50eXBlcy52MS5Qcm9qZWN0UG9pbnRlciKRAQoNUHJvamVjdFN0YXR1cxIuCgpjcmVhdGVkX2F0GAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIOCgZlcnJvcnMYAyADKAkSEAoId2FybmluZ3MYBCADKAki/wIKDlByb2plY3RQb2ludGVyEjQKBnJlbW90ZRgBIAEoCzIiLnR5cGVzLnYxLlByb2plY3RQb2ludGVyLlJlbW90ZUdpdEgAEjYKCWxvY2FsaG9zdBgCIAEoCzIhLnR5cGVzLnYxLlByb2plY3RQb2ludGVyLkxvY2FsR2l0SAASLgoCZGIYAyABKAsyIC50eXBlcy52MS5Qcm9qZWN0UG9pbnRlci5WaXJ0dWFsSAAaVgoJUmVtb3RlR2l0EhIKCnJlbW90ZV91cmwYASABKAkSCwoDcmVmGAIgASgJEhUKDWRhc2hib2FyZF9kaXIYAyABKAkSEQoJYWxlcnRfZGlyGAQgASgJGlUKCExvY2FsR2l0EgwKBHBhdGgYASABKAkSFQoNZGFzaGJvYXJkX2RpchgCIAEoCRIRCglhbGVydF9kaXIYAyABKAkSEQoJcmVhZF9vbmx5GAQgASgIGhYKB1ZpcnR1YWwSCwoDdXJpGAEgASgJQggKBnNjaGVtZUKKAQoMY29tLnR5cGVzLnYxQgxQcm9qZWN0UHJvdG9QAVorZ2l0aHViLmNvbS9taW5pdGFwZS9hcGkvZ28vdHlwZXMvdjE7dHlwZXN2MaICA1RYWKoCCFR5cGVzLlYxygIIVHlwZXNcVjHiAhRUeXBlc1xWMVxHUEJNZXRhZGF0YeoCCVR5cGVzOjpWMWIGcHJvdG8z", [file_google_protobuf_duration, file_google_protobuf_timestamp]);

/**
 * @generated from message types.v1.Project
 */
export type Project = Message<"types.v1.Project"> & {
  /**
   * @generated from field: types.v1.ProjectMeta meta = 1;
   */
  meta?: ProjectMeta;

  /**
   * @generated from field: types.v1.ProjectSpec spec = 2;
   */
  spec?: ProjectSpec;

  /**
   * @generated from field: types.v1.ProjectStatus status = 3;
   */
  status?: ProjectStatus;
};

/**
 * Describes the message types.v1.Project.
 * Use `create(ProjectSchema)` to create a new message.
 */
export const ProjectSchema: GenMessage<Project> = /*@__PURE__*/
  messageDesc(file_types_v1_project, 0);

/**
 * @generated from message types.v1.ProjectMeta
 */
export type ProjectMeta = Message<"types.v1.ProjectMeta"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message types.v1.ProjectMeta.
 * Use `create(ProjectMetaSchema)` to create a new message.
 */
export const ProjectMetaSchema: GenMessage<ProjectMeta> = /*@__PURE__*/
  messageDesc(file_types_v1_project, 1);

/**
 * @generated from message types.v1.ProjectSpec
 */
export type ProjectSpec = Message<"types.v1.ProjectSpec"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: types.v1.ProjectPointer pointer = 2;
   */
  pointer?: ProjectPointer;
};

/**
 * Describes the message types.v1.ProjectSpec.
 * Use `create(ProjectSpecSchema)` to create a new message.
 */
export const ProjectSpecSchema: GenMessage<ProjectSpec> = /*@__PURE__*/
  messageDesc(file_types_v1_project, 2);

/**
 * @generated from message types.v1.ProjectStatus
 */
export type ProjectStatus = Message<"types.v1.ProjectStatus"> & {
  /**
   * @generated from field: google.protobuf.Timestamp created_at = 1;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 2;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: repeated string errors = 3;
   */
  errors: string[];

  /**
   * @generated from field: repeated string warnings = 4;
   */
  warnings: string[];
};

/**
 * Describes the message types.v1.ProjectStatus.
 * Use `create(ProjectStatusSchema)` to create a new message.
 */
export const ProjectStatusSchema: GenMessage<ProjectStatus> = /*@__PURE__*/
  messageDesc(file_types_v1_project, 3);

/**
 * @generated from message types.v1.ProjectPointer
 */
export type ProjectPointer = Message<"types.v1.ProjectPointer"> & {
  /**
   * @generated from oneof types.v1.ProjectPointer.scheme
   */
  scheme: {
    /**
     * @generated from field: types.v1.ProjectPointer.RemoteGit remote = 1;
     */
    value: ProjectPointer_RemoteGit;
    case: "remote";
  } | {
    /**
     * @generated from field: types.v1.ProjectPointer.LocalGit localhost = 2;
     */
    value: ProjectPointer_LocalGit;
    case: "localhost";
  } | {
    /**
     * @generated from field: types.v1.ProjectPointer.Virtual db = 3;
     */
    value: ProjectPointer_Virtual;
    case: "db";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message types.v1.ProjectPointer.
 * Use `create(ProjectPointerSchema)` to create a new message.
 */
export const ProjectPointerSchema: GenMessage<ProjectPointer> = /*@__PURE__*/
  messageDesc(file_types_v1_project, 4);

/**
 * @generated from message types.v1.ProjectPointer.RemoteGit
 */
export type ProjectPointer_RemoteGit = Message<"types.v1.ProjectPointer.RemoteGit"> & {
  /**
   * @generated from field: string remote_url = 1;
   */
  remoteUrl: string;

  /**
   * @generated from field: string ref = 2;
   */
  ref: string;

  /**
   * @generated from field: string dashboard_dir = 3;
   */
  dashboardDir: string;

  /**
   * @generated from field: string alert_dir = 4;
   */
  alertDir: string;
};

/**
 * Describes the message types.v1.ProjectPointer.RemoteGit.
 * Use `create(ProjectPointer_RemoteGitSchema)` to create a new message.
 */
export const ProjectPointer_RemoteGitSchema: GenMessage<ProjectPointer_RemoteGit> = /*@__PURE__*/
  messageDesc(file_types_v1_project, 4, 0);

/**
 * @generated from message types.v1.ProjectPointer.LocalGit
 */
export type ProjectPointer_LocalGit = Message<"types.v1.ProjectPointer.LocalGit"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * @generated from field: string dashboard_dir = 2;
   */
  dashboardDir: string;

  /**
   * @generated from field: string alert_dir = 3;
   */
  alertDir: string;

  /**
   * @generated from field: bool read_only = 4;
   */
  readOnly: boolean;
};

/**
 * Describes the message types.v1.ProjectPointer.LocalGit.
 * Use `create(ProjectPointer_LocalGitSchema)` to create a new message.
 */
export const ProjectPointer_LocalGitSchema: GenMessage<ProjectPointer_LocalGit> = /*@__PURE__*/
  messageDesc(file_types_v1_project, 4, 1);

/**
 * @generated from message types.v1.ProjectPointer.Virtual
 */
export type ProjectPointer_Virtual = Message<"types.v1.ProjectPointer.Virtual"> & {
  /**
   * @generated from field: string uri = 1;
   */
  uri: string;
};

/**
 * Describes the message types.v1.ProjectPointer.Virtual.
 * Use `create(ProjectPointer_VirtualSchema)` to create a new message.
 */
export const ProjectPointer_VirtualSchema: GenMessage<ProjectPointer_Virtual> = /*@__PURE__*/
  messageDesc(file_types_v1_project, 4, 2);

