// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/query_history_entry.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Query } from "./query_pb";
import { file_types_v1_query } from "./query_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/query_history_entry.proto.
 */
export const file_types_v1_query_history_entry: GenFile = /*@__PURE__*/
  fileDesc("CiJ0eXBlcy92MS9xdWVyeV9oaXN0b3J5X2VudHJ5LnByb3RvEgh0eXBlcy52MSKCAQoRUXVlcnlIaXN0b3J5RW50cnkSCgoCaWQYASABKAMSEQoJcmF3X3F1ZXJ5GAIgASgJEh4KBXF1ZXJ5GAMgASgLMg8udHlwZXMudjEuUXVlcnkSLgoKY3JlYXRlZF9hdBgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBClAEKDGNvbS50eXBlcy52MUIWUXVlcnlIaXN0b3J5RW50cnlQcm90b1ABWitnaXRodWIuY29tL21pbml0YXBlL2FwaS9nby90eXBlcy92MTt0eXBlc3YxogIDVFhYqgIIVHlwZXMuVjHKAghUeXBlc1xWMeICFFR5cGVzXFYxXEdQQk1ldGFkYXRh6gIJVHlwZXM6OlYxYgZwcm90bzM", [file_google_protobuf_timestamp, file_types_v1_query]);

/**
 * @generated from message types.v1.QueryHistoryEntry
 */
export type QueryHistoryEntry = Message<"types.v1.QueryHistoryEntry"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string raw_query = 2;
   */
  rawQuery: string;

  /**
   * @generated from field: types.v1.Query query = 3;
   */
  query?: Query;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp;
};

/**
 * Describes the message types.v1.QueryHistoryEntry.
 * Use `create(QueryHistoryEntrySchema)` to create a new message.
 */
export const QueryHistoryEntrySchema: GenMessage<QueryHistoryEntry> = /*@__PURE__*/
  messageDesc(file_types_v1_query_history_entry, 0);

