// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/query_metrics.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Duration } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";
import { file_types_v1_types } from "./types_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/query_metrics.proto.
 */
export const file_types_v1_query_metrics: GenFile = /*@__PURE__*/
  fileDesc("Chx0eXBlcy92MS9xdWVyeV9tZXRyaWNzLnByb3RvEgh0eXBlcy52MSK8BAoMUXVlcnlNZXRyaWNzEhAKCHF1ZXJ5X2lkGAEgASgJEhIKCnF1ZXJ5X3RleHQYAiABKAkSNgoScXVlcnlfc2VudF9sYXRlbmN5GKwCIAEoCzIZLmdvb2dsZS5wcm90b2J1Zi5EdXJhdGlvbhI4ChRmaXJzdF9yZXN1bHRfbGF0ZW5jeRitAiABKAsyGS5nb29nbGUucHJvdG9idWYuRHVyYXRpb24SOAoUZmluYWxfcmVzdWx0X2xhdGVuY3kYrgIgASgLMhkuZ29vZ2xlLnByb3RvYnVmLkR1cmF0aW9uEjAKDXRvdGFsX2xhdGVuY3kYAyABKAsyGS5nb29nbGUucHJvdG9idWYuRHVyYXRpb24SFQoNcm93c19yZXR1cm5lZBgEIAEoAxIUCgxyb3dzX3NjYW5uZWQYBSABKAMSGwoOYnl0ZXNfcmV0dXJuZWQYBiABKANIAIgBARIaCg1ieXRlc19zY2FubmVkGAcgASgDSAGIAQESMQoIZGV0YWlsZWQYCCABKAsyHy50eXBlcy52MS5RdWVyeU1ldHJpY3MuRGV0YWlsZWQaagoIRGV0YWlsZWQSFgoOZXhlY3V0aW9uX3BsYW4YASABKAwSKwoIY3B1X3RpbWUYAiABKAsyGS5nb29nbGUucHJvdG9idWYuRHVyYXRpb24SGQoRbWVtb3J5X3BlYWtfYnl0ZXMYAyABKANCEQoPX2J5dGVzX3JldHVybmVkQhAKDl9ieXRlc19zY2FubmVkQo8BCgxjb20udHlwZXMudjFCEVF1ZXJ5TWV0cmljc1Byb3RvUAFaK2dpdGh1Yi5jb20vbWluaXRhcGUvYXBpL2dvL3R5cGVzL3YxO3R5cGVzdjGiAgNUWFiqAghUeXBlcy5WMcoCCFR5cGVzXFYx4gIUVHlwZXNcVjFcR1BCTWV0YWRhdGHqAglUeXBlczo6VjFiBnByb3RvMw", [file_google_protobuf_duration, file_types_v1_types]);

/**
 * @generated from message types.v1.QueryMetrics
 */
export type QueryMetrics = Message<"types.v1.QueryMetrics"> & {
  /**
   * @generated from field: string query_id = 1;
   */
  queryId: string;

  /**
   * @generated from field: string query_text = 2;
   */
  queryText: string;

  /**
   * Time from query start to query returning. Measures query submission overhead
   * (network round-trip, connection setup).
   *
   * @generated from field: google.protobuf.Duration query_sent_latency = 300;
   */
  querySentLatency?: Duration;

  /**
   * Time from query start to first row ready. Also known as "Time to First Row"
   * (TTFR) or "Time to First Byte" (TTFB). Measures query execution latency on
   * server.
   *
   * @generated from field: google.protobuf.Duration first_result_latency = 301;
   */
  firstResultLatency?: Duration;

  /**
   * Wall-clock time from first row to last row. Measures result fetching
   * duration (not cumulative time spent). Calculated as
   * `lastFetchTime - firstFetchTime`, so include serialization and
   * row-processing overhead.
   *
   * @generated from field: google.protobuf.Duration final_result_latency = 302;
   */
  finalResultLatency?: Duration;

  /**
   * Full end-to-end time from query start to close. Total duration
   * during which the server processed the request.
   *
   * @generated from field: google.protobuf.Duration total_latency = 3;
   */
  totalLatency?: Duration;

  /**
   * @generated from field: int64 rows_returned = 4;
   */
  rowsReturned: bigint;

  /**
   * @generated from field: int64 rows_scanned = 5;
   */
  rowsScanned: bigint;

  /**
   * @generated from field: optional int64 bytes_returned = 6;
   */
  bytesReturned?: bigint;

  /**
   * @generated from field: optional int64 bytes_scanned = 7;
   */
  bytesScanned?: bigint;

  /**
   * @generated from field: types.v1.QueryMetrics.Detailed detailed = 8;
   */
  detailed?: QueryMetrics_Detailed;
};

/**
 * Describes the message types.v1.QueryMetrics.
 * Use `create(QueryMetricsSchema)` to create a new message.
 */
export const QueryMetricsSchema: GenMessage<QueryMetrics> = /*@__PURE__*/
  messageDesc(file_types_v1_query_metrics, 0);

/**
 * @generated from message types.v1.QueryMetrics.Detailed
 */
export type QueryMetrics_Detailed = Message<"types.v1.QueryMetrics.Detailed"> & {
  /**
   * @generated from field: bytes execution_plan = 1;
   */
  executionPlan: Uint8Array;

  /**
   * @generated from field: google.protobuf.Duration cpu_time = 2;
   */
  cpuTime?: Duration;

  /**
   * @generated from field: int64 memory_peak_bytes = 3;
   */
  memoryPeakBytes: bigint;
};

/**
 * Describes the message types.v1.QueryMetrics.Detailed.
 * Use `create(QueryMetrics_DetailedSchema)` to create a new message.
 */
export const QueryMetrics_DetailedSchema: GenMessage<QueryMetrics_Detailed> = /*@__PURE__*/
  messageDesc(file_types_v1_query_metrics, 0, 0);

