// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/release_channel.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/release_channel.proto.
 */
export const file_types_v1_release_channel: GenFile = /*@__PURE__*/
  fileDesc("Ch50eXBlcy92MS9yZWxlYXNlX2NoYW5uZWwucHJvdG8SCHR5cGVzLnYxIjAKDlJlbGVhc2VDaGFubmVsEgwKBG5hbWUYASABKAkSEAoIcHJpb3JpdHkYAiABKAVCkQEKDGNvbS50eXBlcy52MUITUmVsZWFzZUNoYW5uZWxQcm90b1ABWitnaXRodWIuY29tL21pbml0YXBlL2FwaS9nby90eXBlcy92MTt0eXBlc3YxogIDVFhYqgIIVHlwZXMuVjHKAghUeXBlc1xWMeICFFR5cGVzXFYxXEdQQk1ldGFkYXRh6gIJVHlwZXM6OlYxYgZwcm90bzM");

/**
 * @generated from message types.v1.ReleaseChannel
 */
export type ReleaseChannel = Message<"types.v1.ReleaseChannel"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: int32 priority = 2;
   */
  priority: number;
};

/**
 * Describes the message types.v1.ReleaseChannel.
 * Use `create(ReleaseChannelSchema)` to create a new message.
 */
export const ReleaseChannelSchema: GenMessage<ReleaseChannel> = /*@__PURE__*/
  messageDesc(file_types_v1_release_channel, 0);

