// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/subscription.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { PaymentMethod } from "./payment_method_pb";
import { file_types_v1_payment_method } from "./payment_method_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/subscription.proto.
 */
export const file_types_v1_subscription: GenFile = /*@__PURE__*/
  fileDesc("Cht0eXBlcy92MS9zdWJzY3JpcHRpb24ucHJvdG8SCHR5cGVzLnYxItAECgxTdWJzY3JpcHRpb24SLgoKY3JlYXRlZF9hdBhkIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASEQoJc3RyaXBlX2lkGAEgASgJEjcKFmRlZmF1bHRfcGF5bWVudF9tZXRob2QYAiABKAsyFy50eXBlcy52MS5QYXltZW50TWV0aG9kEi0KBnN0YXR1cxgDIAEoDjIdLnR5cGVzLnYxLlN1YnNjcmlwdGlvbi5TdGF0dXMSPAoXY3VycmVudF9wZXJpb2Rfc3RhcnRfYXQYyQEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBI6ChVjdXJyZW50X3BlcmlvZF9lbmRfYXQYygEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgljYW5jZWxfYXQYrQIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIwCgtjYW5jZWxlZF9hdBiuAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi0KCGVuZGVkX2F0GJEDIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAiiQEKBlN0YXR1cxILCgdVbmtub3duEAASCgoGQWN0aXZlEAESDAoIQ2FuY2VsZWQQAhIOCgpJbmNvbXBsZXRlEAMSFQoRSW5jb21wbGV0ZUV4cGlyZWQQBBILCgdQYXN0RHVlEAUSCgoGUGF1c2VkEAYSDAoIVHJpYWxpbmcQBxIKCgZVbnBhaWQQCEKPAQoMY29tLnR5cGVzLnYxQhFTdWJzY3JpcHRpb25Qcm90b1ABWitnaXRodWIuY29tL21pbml0YXBlL2FwaS9nby90eXBlcy92MTt0eXBlc3YxogIDVFhYqgIIVHlwZXMuVjHKAghUeXBlc1xWMeICFFR5cGVzXFYxXEdQQk1ldGFkYXRh6gIJVHlwZXM6OlYxYgZwcm90bzM", [file_google_protobuf_timestamp, file_types_v1_payment_method]);

/**
 * @generated from message types.v1.Subscription
 */
export type Subscription = Message<"types.v1.Subscription"> & {
  /**
   * @generated from field: google.protobuf.Timestamp created_at = 100;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: string stripe_id = 1;
   */
  stripeId: string;

  /**
   * @generated from field: types.v1.PaymentMethod default_payment_method = 2;
   */
  defaultPaymentMethod?: PaymentMethod;

  /**
   * @generated from field: types.v1.Subscription.Status status = 3;
   */
  status: Subscription_Status;

  /**
   * @generated from field: google.protobuf.Timestamp current_period_start_at = 201;
   */
  currentPeriodStartAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp current_period_end_at = 202;
   */
  currentPeriodEndAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp cancel_at = 301;
   */
  cancelAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp canceled_at = 302;
   */
  canceledAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp ended_at = 401;
   */
  endedAt?: Timestamp;
};

/**
 * Describes the message types.v1.Subscription.
 * Use `create(SubscriptionSchema)` to create a new message.
 */
export const SubscriptionSchema: GenMessage<Subscription> = /*@__PURE__*/
  messageDesc(file_types_v1_subscription, 0);

/**
 * @generated from enum types.v1.Subscription.Status
 */
export enum Subscription_Status {
  /**
   * @generated from enum value: Unknown = 0;
   */
  Unknown = 0,

  /**
   * @generated from enum value: Active = 1;
   */
  Active = 1,

  /**
   * @generated from enum value: Canceled = 2;
   */
  Canceled = 2,

  /**
   * @generated from enum value: Incomplete = 3;
   */
  Incomplete = 3,

  /**
   * @generated from enum value: IncompleteExpired = 4;
   */
  IncompleteExpired = 4,

  /**
   * @generated from enum value: PastDue = 5;
   */
  PastDue = 5,

  /**
   * @generated from enum value: Paused = 6;
   */
  Paused = 6,

  /**
   * @generated from enum value: Trialing = 7;
   */
  Trialing = 7,

  /**
   * @generated from enum value: Unpaid = 8;
   */
  Unpaid = 8,
}

/**
 * Describes the enum types.v1.Subscription.Status.
 */
export const Subscription_StatusSchema: GenEnum<Subscription_Status> = /*@__PURE__*/
  enumDesc(file_types_v1_subscription, 0, 0);

