// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/symbol.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { VarType } from "./types_pb";
import { file_types_v1_types } from "./types_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/symbol.proto.
 */
export const file_types_v1_symbol: GenFile = /*@__PURE__*/
  fileDesc("ChV0eXBlcy92MS9zeW1ib2wucHJvdG8SCHR5cGVzLnYxIjcKBlN5bWJvbBIMCgRuYW1lGAEgASgJEh8KBHR5cGUYAiABKAsyES50eXBlcy52MS5WYXJUeXBlQokBCgxjb20udHlwZXMudjFCC1N5bWJvbFByb3RvUAFaK2dpdGh1Yi5jb20vbWluaXRhcGUvYXBpL2dvL3R5cGVzL3YxO3R5cGVzdjGiAgNUWFiqAghUeXBlcy5WMcoCCFR5cGVzXFYx4gIUVHlwZXNcVjFcR1BCTWV0YWRhdGHqAglUeXBlczo6VjFiBnByb3RvMw", [file_types_v1_types]);

/**
 * @generated from message types.v1.Symbol
 */
export type Symbol = Message<"types.v1.Symbol"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: types.v1.VarType type = 2;
   */
  type?: VarType;
};

/**
 * Describes the message types.v1.Symbol.
 * Use `create(SymbolSchema)` to create a new message.
 */
export const SymbolSchema: GenMessage<Symbol> = /*@__PURE__*/
  messageDesc(file_types_v1_symbol, 0);

