// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/ulid.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/ulid.proto.
 */
export const file_types_v1_ulid: GenFile = /*@__PURE__*/
  fileDesc("ChN0eXBlcy92MS91bGlkLnByb3RvEgh0eXBlcy52MSIhCgRVTElEEgwKBEhpZ2gYASABKAQSCwoDTG93GAIgASgEQocBCgxjb20udHlwZXMudjFCCVVsaWRQcm90b1ABWitnaXRodWIuY29tL21pbml0YXBlL2FwaS9nby90eXBlcy92MTt0eXBlc3YxogIDVFhYqgIIVHlwZXMuVjHKAghUeXBlc1xWMeICFFR5cGVzXFYxXEdQQk1ldGFkYXRh6gIJVHlwZXM6OlYxYgZwcm90bzM");

/**
 * @generated from message types.v1.ULID
 */
export type ULID = Message<"types.v1.ULID"> & {
  /**
   * @generated from field: uint64 High = 1;
   */
  High: bigint;

  /**
   * @generated from field: uint64 Low = 2;
   */
  Low: bigint;
};

/**
 * Describes the message types.v1.ULID.
 * Use `create(ULIDSchema)` to create a new message.
 */
export const ULIDSchema: GenMessage<ULID> = /*@__PURE__*/
  messageDesc(file_types_v1_ulid, 0);

