// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/user_token.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/user_token.proto.
 */
export const file_types_v1_user_token: GenFile = /*@__PURE__*/
  fileDesc("Chl0eXBlcy92MS91c2VyX3Rva2VuLnByb3RvEgh0eXBlcy52MSJNCglVc2VyVG9rZW4SDwoHdXNlcl9pZBgBIAEoAxINCgV0b2tlbhgCIAEoCRIQCgh1c2VybmFtZRgDIAEoCRIOCgZvcmdfaWQYBCABKANCjAEKDGNvbS50eXBlcy52MUIOVXNlclRva2VuUHJvdG9QAVorZ2l0aHViLmNvbS9taW5pdGFwZS9hcGkvZ28vdHlwZXMvdjE7dHlwZXN2MaICA1RYWKoCCFR5cGVzLlYxygIIVHlwZXNcVjHiAhRUeXBlc1xWMVxHUEJNZXRhZGF0YeoCCVR5cGVzOjpWMWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message types.v1.UserToken
 */
export type UserToken = Message<"types.v1.UserToken"> & {
  /**
   * @generated from field: int64 user_id = 1;
   */
  userId: bigint;

  /**
   * @generated from field: string token = 2;
   */
  token: string;

  /**
   * @generated from field: string username = 3;
   */
  username: string;

  /**
   * @generated from field: int64 org_id = 4;
   */
  orgId: bigint;
};

/**
 * Describes the message types.v1.UserToken.
 * Use `create(UserTokenSchema)` to create a new message.
 */
export const UserTokenSchema: GenMessage<UserToken> = /*@__PURE__*/
  messageDesc(file_types_v1_user_token, 0);

