// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/version.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/version.proto.
 */
export const file_types_v1_version: GenFile = /*@__PURE__*/
  fileDesc("ChZ0eXBlcy92MS92ZXJzaW9uLnByb3RvEgh0eXBlcy52MSJaCgdWZXJzaW9uEg0KBW1ham9yGAEgASgFEg0KBW1pbm9yGAIgASgFEg0KBXBhdGNoGAMgASgFEhMKC3ByZXJlbGVhc2VzGAQgAygJEg0KBWJ1aWxkGAUgASgJQooBCgxjb20udHlwZXMudjFCDFZlcnNpb25Qcm90b1ABWitnaXRodWIuY29tL21pbml0YXBlL2FwaS9nby90eXBlcy92MTt0eXBlc3YxogIDVFhYqgIIVHlwZXMuVjHKAghUeXBlc1xWMeICFFR5cGVzXFYxXEdQQk1ldGFkYXRh6gIJVHlwZXM6OlYxYgZwcm90bzM");

/**
 * @generated from message types.v1.Version
 */
export type Version = Message<"types.v1.Version"> & {
  /**
   * @generated from field: int32 major = 1;
   */
  major: number;

  /**
   * @generated from field: int32 minor = 2;
   */
  minor: number;

  /**
   * @generated from field: int32 patch = 3;
   */
  patch: number;

  /**
   * @generated from field: repeated string prereleases = 4;
   */
  prereleases: string[];

  /**
   * @generated from field: string build = 5;
   */
  build: string;
};

/**
 * Describes the message types.v1.Version.
 * Use `create(VersionSchema)` to create a new message.
 */
export const VersionSchema: GenMessage<Version> = /*@__PURE__*/
  messageDesc(file_types_v1_version, 0);

