// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/version_artifact.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/version_artifact.proto.
 */
export const file_types_v1_version_artifact: GenFile = /*@__PURE__*/
  fileDesc("Ch90eXBlcy92MS92ZXJzaW9uX2FydGlmYWN0LnByb3RvEgh0eXBlcy52MSJxCg9WZXJzaW9uQXJ0aWZhY3QSCwoDdXJsGAEgASgJEg4KBnNoYTI1NhgCIAEoCRIRCglzaWduYXR1cmUYAyABKAkSFAoMYXJjaGl0ZWN0dXJlGAQgASgJEhgKEG9wZXJhdGluZ19zeXN0ZW0YBSABKAlCkgEKDGNvbS50eXBlcy52MUIUVmVyc2lvbkFydGlmYWN0UHJvdG9QAVorZ2l0aHViLmNvbS9taW5pdGFwZS9hcGkvZ28vdHlwZXMvdjE7dHlwZXN2MaICA1RYWKoCCFR5cGVzLlYxygIIVHlwZXNcVjHiAhRUeXBlc1xWMVxHUEJNZXRhZGF0YeoCCVR5cGVzOjpWMWIGcHJvdG8z");

/**
 * @generated from message types.v1.VersionArtifact
 */
export type VersionArtifact = Message<"types.v1.VersionArtifact"> & {
  /**
   * @generated from field: string url = 1;
   */
  url: string;

  /**
   * @generated from field: string sha256 = 2;
   */
  sha256: string;

  /**
   * @generated from field: string signature = 3;
   */
  signature: string;

  /**
   * @generated from field: string architecture = 4;
   */
  architecture: string;

  /**
   * @generated from field: string operating_system = 5;
   */
  operatingSystem: string;
};

/**
 * Describes the message types.v1.VersionArtifact.
 * Use `create(VersionArtifactSchema)` to create a new message.
 */
export const VersionArtifactSchema: GenMessage<VersionArtifact> = /*@__PURE__*/
  messageDesc(file_types_v1_version_artifact, 0);

