// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file svc/ingest/v1/service.proto (package svc.ingest.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import { file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";
import type { Log } from "../../../types/v1/otel_logging_pb";
import { file_types_v1_otel_logging } from "../../../types/v1/otel_logging_pb";
import type { Resource } from "../../../types/v1/otel_resource_pb";
import { file_types_v1_otel_resource } from "../../../types/v1/otel_resource_pb";
import type { Scope } from "../../../types/v1/otel_scope_pb";
import { file_types_v1_otel_scope } from "../../../types/v1/otel_scope_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file svc/ingest/v1/service.proto.
 */
export const file_svc_ingest_v1_service: GenFile = /*@__PURE__*/
  fileDesc("ChtzdmMvaW5nZXN0L3YxL3NlcnZpY2UucHJvdG8SDXN2Yy5pbmdlc3QudjEiigEKDUluZ2VzdFJlcXVlc3QSLAoIcmVzb3VyY2UYASABKAsyEi50eXBlcy52MS5SZXNvdXJjZUIGukgDyAEBEiYKBXNjb3BlGAIgASgLMg8udHlwZXMudjEuU2NvcGVCBrpIA8gBARIjCgRsb2dzGAMgAygLMg0udHlwZXMudjEuTG9nQga6SAPIAQEiEAoOSW5nZXN0UmVzcG9uc2UikAEKE0luZ2VzdFN0cmVhbVJlcXVlc3QSLAoIcmVzb3VyY2UYASABKAsyEi50eXBlcy52MS5SZXNvdXJjZUIGukgDyAEBEiYKBXNjb3BlGAIgASgLMg8udHlwZXMudjEuU2NvcGVCBrpIA8gBARIjCgRsb2dzGAMgAygLMg0udHlwZXMudjEuTG9nQga6SAPIAQEiFgoUSW5nZXN0U3RyZWFtUmVzcG9uc2UysQEKDUluZ2VzdFNlcnZpY2USRQoGSW5nZXN0Ehwuc3ZjLmluZ2VzdC52MS5Jbmdlc3RSZXF1ZXN0Gh0uc3ZjLmluZ2VzdC52MS5Jbmdlc3RSZXNwb25zZRJZCgxJbmdlc3RTdHJlYW0SIi5zdmMuaW5nZXN0LnYxLkluZ2VzdFN0cmVhbVJlcXVlc3QaIy5zdmMuaW5nZXN0LnYxLkluZ2VzdFN0cmVhbVJlc3BvbnNlKAFCqgEKEWNvbS5zdmMuaW5nZXN0LnYxQgxTZXJ2aWNlUHJvdG9QAVoxZ2l0aHViLmNvbS9taW5pdGFwZS9hcGkvZ28vc3ZjL2luZ2VzdC92MTtpbmdlc3R2MaICA1NJWKoCDVN2Yy5Jbmdlc3QuVjHKAg1TdmNcSW5nZXN0XFYx4gIZU3ZjXEluZ2VzdFxWMVxHUEJNZXRhZGF0YeoCD1N2Yzo6SW5nZXN0OjpWMWIGcHJvdG8z", [file_buf_validate_validate, file_google_protobuf_duration, file_types_v1_otel_logging, file_types_v1_otel_resource, file_types_v1_otel_scope]);

/**
 * @generated from message svc.ingest.v1.IngestRequest
 */
export type IngestRequest = Message<"svc.ingest.v1.IngestRequest"> & {
  /**
   * @generated from field: types.v1.Resource resource = 1;
   */
  resource?: Resource;

  /**
   * @generated from field: types.v1.Scope scope = 2;
   */
  scope?: Scope;

  /**
   * @generated from field: repeated types.v1.Log logs = 3;
   */
  logs: Log[];
};

/**
 * Describes the message svc.ingest.v1.IngestRequest.
 * Use `create(IngestRequestSchema)` to create a new message.
 */
export const IngestRequestSchema: GenMessage<IngestRequest> = /*@__PURE__*/
  messageDesc(file_svc_ingest_v1_service, 0);

/**
 * @generated from message svc.ingest.v1.IngestResponse
 */
export type IngestResponse = Message<"svc.ingest.v1.IngestResponse"> & {
};

/**
 * Describes the message svc.ingest.v1.IngestResponse.
 * Use `create(IngestResponseSchema)` to create a new message.
 */
export const IngestResponseSchema: GenMessage<IngestResponse> = /*@__PURE__*/
  messageDesc(file_svc_ingest_v1_service, 1);

/**
 * @generated from message svc.ingest.v1.IngestStreamRequest
 */
export type IngestStreamRequest = Message<"svc.ingest.v1.IngestStreamRequest"> & {
  /**
   * only evaluated on the first message
   *
   * @generated from field: types.v1.Resource resource = 1;
   */
  resource?: Resource;

  /**
   * @generated from field: types.v1.Scope scope = 2;
   */
  scope?: Scope;

  /**
   * @generated from field: repeated types.v1.Log logs = 3;
   */
  logs: Log[];
};

/**
 * Describes the message svc.ingest.v1.IngestStreamRequest.
 * Use `create(IngestStreamRequestSchema)` to create a new message.
 */
export const IngestStreamRequestSchema: GenMessage<IngestStreamRequest> = /*@__PURE__*/
  messageDesc(file_svc_ingest_v1_service, 2);

/**
 * @generated from message svc.ingest.v1.IngestStreamResponse
 */
export type IngestStreamResponse = Message<"svc.ingest.v1.IngestStreamResponse"> & {
};

/**
 * Describes the message svc.ingest.v1.IngestStreamResponse.
 * Use `create(IngestStreamResponseSchema)` to create a new message.
 */
export const IngestStreamResponseSchema: GenMessage<IngestStreamResponse> = /*@__PURE__*/
  messageDesc(file_svc_ingest_v1_service, 3);

/**
 * @generated from service svc.ingest.v1.IngestService
 */
export const IngestService: GenService<{
  /**
   * @generated from rpc svc.ingest.v1.IngestService.Ingest
   */
  ingest: {
    methodKind: "unary";
    input: typeof IngestRequestSchema;
    output: typeof IngestResponseSchema;
  },
  /**
   * @generated from rpc svc.ingest.v1.IngestService.IngestStream
   */
  ingestStream: {
    methodKind: "client_streaming";
    input: typeof IngestStreamRequestSchema;
    output: typeof IngestStreamResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_svc_ingest_v1_service, 0);

