// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file svc/feature/v1/service.proto (package svc.feature.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Feature } from "../../../types/v1/feature_pb";
import { file_types_v1_feature } from "../../../types/v1/feature_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file svc/feature/v1/service.proto.
 */
export const file_svc_feature_v1_service: GenFile = /*@__PURE__*/
  fileDesc("ChxzdmMvZmVhdHVyZS92MS9zZXJ2aWNlLnByb3RvEg5zdmMuZmVhdHVyZS52MSIkChFIYXNGZWF0dXJlUmVxdWVzdBIPCgdmZWF0dXJlGAEgASgJIicKEkhhc0ZlYXR1cmVSZXNwb25zZRIRCglhdmFpbGFibGUYASABKAgiFAoSTGlzdEZlYXR1cmVSZXF1ZXN0IjoKE0xpc3RGZWF0dXJlUmVzcG9uc2USIwoIZmVhdHVyZXMYASADKAsyES50eXBlcy52MS5GZWF0dXJlIhUKE0FsbG93ZWRVc2FnZVJlcXVlc3QiqgEKFEFsbG93ZWRVc2FnZVJlc3BvbnNlEkwKD2xvY2FsaG9zdF91c2FnZRgBIAEoDjIzLnN2Yy5mZWF0dXJlLnYxLkFsbG93ZWRVc2FnZVJlc3BvbnNlLkxvY2FsaG9zdFVzYWdlIkQKDkxvY2FsaG9zdFVzYWdlEgwKCE5PX1VTQUdFEAASEAoMUEVSU09OQUxfVVNFEAESEgoOQ09NTUVSQ0lBTF9VU0UQAjKYAgoORmVhdHVyZVNlcnZpY2USUwoKSGFzRmVhdHVyZRIhLnN2Yy5mZWF0dXJlLnYxLkhhc0ZlYXR1cmVSZXF1ZXN0GiIuc3ZjLmZlYXR1cmUudjEuSGFzRmVhdHVyZVJlc3BvbnNlElYKC0xpc3RGZWF0dXJlEiIuc3ZjLmZlYXR1cmUudjEuTGlzdEZlYXR1cmVSZXF1ZXN0GiMuc3ZjLmZlYXR1cmUudjEuTGlzdEZlYXR1cmVSZXNwb25zZRJZCgxBbGxvd2VkVXNhZ2USIy5zdmMuZmVhdHVyZS52MS5BbGxvd2VkVXNhZ2VSZXF1ZXN0GiQuc3ZjLmZlYXR1cmUudjEuQWxsb3dlZFVzYWdlUmVzcG9uc2VCsQEKEmNvbS5zdmMuZmVhdHVyZS52MUIMU2VydmljZVByb3RvUAFaM2dpdGh1Yi5jb20vbWluaXRhcGUvYXBpL2dvL3N2Yy9mZWF0dXJlL3YxO2ZlYXR1cmV2MaICA1NGWKoCDlN2Yy5GZWF0dXJlLlYxygIOU3ZjXEZlYXR1cmVcVjHiAhpTdmNcRmVhdHVyZVxWMVxHUEJNZXRhZGF0YeoCEFN2Yzo6RmVhdHVyZTo6VjFiBnByb3RvMw", [file_types_v1_feature]);

/**
 * @generated from message svc.feature.v1.HasFeatureRequest
 */
export type HasFeatureRequest = Message<"svc.feature.v1.HasFeatureRequest"> & {
  /**
   * @generated from field: string feature = 1;
   */
  feature: string;
};

/**
 * Describes the message svc.feature.v1.HasFeatureRequest.
 * Use `create(HasFeatureRequestSchema)` to create a new message.
 */
export const HasFeatureRequestSchema: GenMessage<HasFeatureRequest> = /*@__PURE__*/
  messageDesc(file_svc_feature_v1_service, 0);

/**
 * @generated from message svc.feature.v1.HasFeatureResponse
 */
export type HasFeatureResponse = Message<"svc.feature.v1.HasFeatureResponse"> & {
  /**
   * @generated from field: bool available = 1;
   */
  available: boolean;
};

/**
 * Describes the message svc.feature.v1.HasFeatureResponse.
 * Use `create(HasFeatureResponseSchema)` to create a new message.
 */
export const HasFeatureResponseSchema: GenMessage<HasFeatureResponse> = /*@__PURE__*/
  messageDesc(file_svc_feature_v1_service, 1);

/**
 * @generated from message svc.feature.v1.ListFeatureRequest
 */
export type ListFeatureRequest = Message<"svc.feature.v1.ListFeatureRequest"> & {
};

/**
 * Describes the message svc.feature.v1.ListFeatureRequest.
 * Use `create(ListFeatureRequestSchema)` to create a new message.
 */
export const ListFeatureRequestSchema: GenMessage<ListFeatureRequest> = /*@__PURE__*/
  messageDesc(file_svc_feature_v1_service, 2);

/**
 * @generated from message svc.feature.v1.ListFeatureResponse
 */
export type ListFeatureResponse = Message<"svc.feature.v1.ListFeatureResponse"> & {
  /**
   * @generated from field: repeated types.v1.Feature features = 1;
   */
  features: Feature[];
};

/**
 * Describes the message svc.feature.v1.ListFeatureResponse.
 * Use `create(ListFeatureResponseSchema)` to create a new message.
 */
export const ListFeatureResponseSchema: GenMessage<ListFeatureResponse> = /*@__PURE__*/
  messageDesc(file_svc_feature_v1_service, 3);

/**
 * @generated from message svc.feature.v1.AllowedUsageRequest
 */
export type AllowedUsageRequest = Message<"svc.feature.v1.AllowedUsageRequest"> & {
};

/**
 * Describes the message svc.feature.v1.AllowedUsageRequest.
 * Use `create(AllowedUsageRequestSchema)` to create a new message.
 */
export const AllowedUsageRequestSchema: GenMessage<AllowedUsageRequest> = /*@__PURE__*/
  messageDesc(file_svc_feature_v1_service, 4);

/**
 * @generated from message svc.feature.v1.AllowedUsageResponse
 */
export type AllowedUsageResponse = Message<"svc.feature.v1.AllowedUsageResponse"> & {
  /**
   * @generated from field: svc.feature.v1.AllowedUsageResponse.LocalhostUsage localhost_usage = 1;
   */
  localhostUsage: AllowedUsageResponse_LocalhostUsage;
};

/**
 * Describes the message svc.feature.v1.AllowedUsageResponse.
 * Use `create(AllowedUsageResponseSchema)` to create a new message.
 */
export const AllowedUsageResponseSchema: GenMessage<AllowedUsageResponse> = /*@__PURE__*/
  messageDesc(file_svc_feature_v1_service, 5);

/**
 * @generated from enum svc.feature.v1.AllowedUsageResponse.LocalhostUsage
 */
export enum AllowedUsageResponse_LocalhostUsage {
  /**
   * @generated from enum value: NO_USAGE = 0;
   */
  NO_USAGE = 0,

  /**
   * @generated from enum value: PERSONAL_USE = 1;
   */
  PERSONAL_USE = 1,

  /**
   * @generated from enum value: COMMERCIAL_USE = 2;
   */
  COMMERCIAL_USE = 2,
}

/**
 * Describes the enum svc.feature.v1.AllowedUsageResponse.LocalhostUsage.
 */
export const AllowedUsageResponse_LocalhostUsageSchema: GenEnum<AllowedUsageResponse_LocalhostUsage> = /*@__PURE__*/
  enumDesc(file_svc_feature_v1_service, 5, 0);

/**
 * @generated from service svc.feature.v1.FeatureService
 */
export const FeatureService: GenService<{
  /**
   * @generated from rpc svc.feature.v1.FeatureService.HasFeature
   */
  hasFeature: {
    methodKind: "unary";
    input: typeof HasFeatureRequestSchema;
    output: typeof HasFeatureResponseSchema;
  },
  /**
   * @generated from rpc svc.feature.v1.FeatureService.ListFeature
   */
  listFeature: {
    methodKind: "unary";
    input: typeof ListFeatureRequestSchema;
    output: typeof ListFeatureResponseSchema;
  },
  /**
   * @generated from rpc svc.feature.v1.FeatureService.AllowedUsage
   */
  allowedUsage: {
    methodKind: "unary";
    input: typeof AllowedUsageRequestSchema;
    output: typeof AllowedUsageResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_svc_feature_v1_service, 0);

