// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=none"
// @generated from file svc/environment/v1/service.proto (package svc.environment.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Cursor } from "../../../types/v1/cursor_pb";
import { file_types_v1_cursor } from "../../../types/v1/cursor_pb";
import { file_types_v1_environment } from "../../../types/v1/environment_pb";
import type { Resource } from "../../../types/v1/otel_resource_pb";
import { file_types_v1_otel_resource } from "../../../types/v1/otel_resource_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file svc/environment/v1/service.proto.
 */
export const file_svc_environment_v1_service: GenFile = /*@__PURE__*/
  fileDesc("CiBzdmMvZW52aXJvbm1lbnQvdjEvc2VydmljZS5wcm90bxISc3ZjLmVudmlyb25tZW50LnYxIl4KE0xpc3RSZXNvdXJjZVJlcXVlc3QSIAoGY3Vyc29yGAEgASgLMhAudHlwZXMudjEuQ3Vyc29yEg0KBWxpbWl0GAIgASgFEhYKDmVudmlyb25tZW50X2lkGAMgASgDIqoBChRMaXN0UmVzb3VyY2VSZXNwb25zZRIeCgRuZXh0GAEgASgLMhAudHlwZXMudjEuQ3Vyc29yEkAKBWl0ZW1zGAIgAygLMjEuc3ZjLmVudmlyb25tZW50LnYxLkxpc3RSZXNvdXJjZVJlc3BvbnNlLkxpc3RJdGVtGjAKCExpc3RJdGVtEiQKCHJlc291cmNlGAEgASgLMhIudHlwZXMudjEuUmVzb3VyY2Ui+AMKC1RyaW1SZXF1ZXN0EhYKDmVudmlyb25tZW50X2lkGAEgASgDEjYKBHNpemUYAiABKAsyJi5zdmMuZW52aXJvbm1lbnQudjEuVHJpbVJlcXVlc3QuQnlTaXplSAASNgoEdGltZRgDIAEoCzImLnN2Yy5lbnZpcm9ubWVudC52MS5UcmltUmVxdWVzdC5CeVRpbWVIABp8CgZCeVNpemUSFQoIbG9nX3NpemUYASABKARIAIgBARIWCglzcGFuX3NpemUYAiABKARIAYgBARIYCgttZXRyaWNfc2l6ZRgDIAEoBEgCiAEBQgsKCV9sb2dfc2l6ZUIMCgpfc3Bhbl9zaXplQg4KDF9tZXRyaWNfc2l6ZRrcAQoGQnlUaW1lEjMKCm9sZGVzdF9sb2cYASABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wSACIAQESNAoLb2xkZXN0X3NwYW4YAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wSAGIAQESNgoNb2xkZXN0X21ldHJpYxgDIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBIAogBAUINCgtfb2xkZXN0X2xvZ0IOCgxfb2xkZXN0X3NwYW5CEAoOX29sZGVzdF9tZXRyaWNCBAoCYnkiHwoMVHJpbVJlc3BvbnNlEg8KB3RyaW1tZWQYASABKAQywgEKEkVudmlyb25tZW50U2VydmljZRJhCgxMaXN0UmVzb3VyY2USJy5zdmMuZW52aXJvbm1lbnQudjEuTGlzdFJlc291cmNlUmVxdWVzdBooLnN2Yy5lbnZpcm9ubWVudC52MS5MaXN0UmVzb3VyY2VSZXNwb25zZRJJCgRUcmltEh8uc3ZjLmVudmlyb25tZW50LnYxLlRyaW1SZXF1ZXN0GiAuc3ZjLmVudmlyb25tZW50LnYxLlRyaW1SZXNwb25zZULNAQoWY29tLnN2Yy5lbnZpcm9ubWVudC52MUIMU2VydmljZVByb3RvUAFaO2dpdGh1Yi5jb20vbWluaXRhcGUvYXBpL2dvL3N2Yy9lbnZpcm9ubWVudC92MTtlbnZpcm9ubWVudHYxogIDU0VYqgISU3ZjLkVudmlyb25tZW50LlYxygISU3ZjXEVudmlyb25tZW50XFYx4gIeU3ZjXEVudmlyb25tZW50XFYxXEdQQk1ldGFkYXRh6gIUU3ZjOjpFbnZpcm9ubWVudDo6VjFiBnByb3RvMw", [file_google_protobuf_timestamp, file_types_v1_cursor, file_types_v1_environment, file_types_v1_otel_resource]);

/**
 * @generated from message svc.environment.v1.ListResourceRequest
 */
export type ListResourceRequest = Message<"svc.environment.v1.ListResourceRequest"> & {
  /**
   * @generated from field: types.v1.Cursor cursor = 1;
   */
  cursor?: Cursor;

  /**
   * @generated from field: int32 limit = 2;
   */
  limit: number;

  /**
   * @generated from field: int64 environment_id = 3;
   */
  environmentId: bigint;
};

/**
 * Describes the message svc.environment.v1.ListResourceRequest.
 * Use `create(ListResourceRequestSchema)` to create a new message.
 */
export const ListResourceRequestSchema: GenMessage<ListResourceRequest> = /*@__PURE__*/
  messageDesc(file_svc_environment_v1_service, 0);

/**
 * @generated from message svc.environment.v1.ListResourceResponse
 */
export type ListResourceResponse = Message<"svc.environment.v1.ListResourceResponse"> & {
  /**
   * @generated from field: types.v1.Cursor next = 1;
   */
  next?: Cursor;

  /**
   * @generated from field: repeated svc.environment.v1.ListResourceResponse.ListItem items = 2;
   */
  items: ListResourceResponse_ListItem[];
};

/**
 * Describes the message svc.environment.v1.ListResourceResponse.
 * Use `create(ListResourceResponseSchema)` to create a new message.
 */
export const ListResourceResponseSchema: GenMessage<ListResourceResponse> = /*@__PURE__*/
  messageDesc(file_svc_environment_v1_service, 1);

/**
 * @generated from message svc.environment.v1.ListResourceResponse.ListItem
 */
export type ListResourceResponse_ListItem = Message<"svc.environment.v1.ListResourceResponse.ListItem"> & {
  /**
   * @generated from field: types.v1.Resource resource = 1;
   */
  resource?: Resource;
};

/**
 * Describes the message svc.environment.v1.ListResourceResponse.ListItem.
 * Use `create(ListResourceResponse_ListItemSchema)` to create a new message.
 */
export const ListResourceResponse_ListItemSchema: GenMessage<ListResourceResponse_ListItem> = /*@__PURE__*/
  messageDesc(file_svc_environment_v1_service, 1, 0);

/**
 * @generated from message svc.environment.v1.TrimRequest
 */
export type TrimRequest = Message<"svc.environment.v1.TrimRequest"> & {
  /**
   * @generated from field: int64 environment_id = 1;
   */
  environmentId: bigint;

  /**
   * @generated from oneof svc.environment.v1.TrimRequest.by
   */
  by: {
    /**
     * @generated from field: svc.environment.v1.TrimRequest.BySize size = 2;
     */
    value: TrimRequest_BySize;
    case: "size";
  } | {
    /**
     * @generated from field: svc.environment.v1.TrimRequest.ByTime time = 3;
     */
    value: TrimRequest_ByTime;
    case: "time";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message svc.environment.v1.TrimRequest.
 * Use `create(TrimRequestSchema)` to create a new message.
 */
export const TrimRequestSchema: GenMessage<TrimRequest> = /*@__PURE__*/
  messageDesc(file_svc_environment_v1_service, 2);

/**
 * @generated from message svc.environment.v1.TrimRequest.BySize
 */
export type TrimRequest_BySize = Message<"svc.environment.v1.TrimRequest.BySize"> & {
  /**
   * @generated from field: optional uint64 log_size = 1;
   */
  logSize?: bigint;

  /**
   * @generated from field: optional uint64 span_size = 2;
   */
  spanSize?: bigint;

  /**
   * @generated from field: optional uint64 metric_size = 3;
   */
  metricSize?: bigint;
};

/**
 * Describes the message svc.environment.v1.TrimRequest.BySize.
 * Use `create(TrimRequest_BySizeSchema)` to create a new message.
 */
export const TrimRequest_BySizeSchema: GenMessage<TrimRequest_BySize> = /*@__PURE__*/
  messageDesc(file_svc_environment_v1_service, 2, 0);

/**
 * @generated from message svc.environment.v1.TrimRequest.ByTime
 */
export type TrimRequest_ByTime = Message<"svc.environment.v1.TrimRequest.ByTime"> & {
  /**
   * @generated from field: optional google.protobuf.Timestamp oldest_log = 1;
   */
  oldestLog?: Timestamp;

  /**
   * @generated from field: optional google.protobuf.Timestamp oldest_span = 2;
   */
  oldestSpan?: Timestamp;

  /**
   * @generated from field: optional google.protobuf.Timestamp oldest_metric = 3;
   */
  oldestMetric?: Timestamp;
};

/**
 * Describes the message svc.environment.v1.TrimRequest.ByTime.
 * Use `create(TrimRequest_ByTimeSchema)` to create a new message.
 */
export const TrimRequest_ByTimeSchema: GenMessage<TrimRequest_ByTime> = /*@__PURE__*/
  messageDesc(file_svc_environment_v1_service, 2, 1);

/**
 * @generated from message svc.environment.v1.TrimResponse
 */
export type TrimResponse = Message<"svc.environment.v1.TrimResponse"> & {
  /**
   * @generated from field: uint64 trimmed = 1;
   */
  trimmed: bigint;
};

/**
 * Describes the message svc.environment.v1.TrimResponse.
 * Use `create(TrimResponseSchema)` to create a new message.
 */
export const TrimResponseSchema: GenMessage<TrimResponse> = /*@__PURE__*/
  messageDesc(file_svc_environment_v1_service, 3);

/**
 * @generated from service svc.environment.v1.EnvironmentService
 */
export const EnvironmentService: GenService<{
  /**
   * @generated from rpc svc.environment.v1.EnvironmentService.ListResource
   */
  listResource: {
    methodKind: "unary";
    input: typeof ListResourceRequestSchema;
    output: typeof ListResourceResponseSchema;
  },
  /**
   * @generated from rpc svc.environment.v1.EnvironmentService.Trim
   */
  trim: {
    methodKind: "unary";
    input: typeof TrimRequestSchema;
    output: typeof TrimResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_svc_environment_v1_service, 0);

